function out = manual_smoke_stage05_formal_suite()
startup;

pm = struct();
pm.enable_monitor = true;
pm.enable_comm_bytes = true;
pm.enable_slow_iter_warn = true;
pm.slow_iter_threshold_sec = 0.5;
pm.enable_per_point_debug = false;
pm.enable_dataqueue = true;
pm.per_point_log_level = 'DEBUG';

artifact_root = fullfile('outputs','experiments','chapter4','stage05_formal_suite','smoke');

out = run_stage05_formal_suite( ...
    'i_grid_deg', [60], ...
    'P_grid', [8 10], ...
    'T_grid', [8 10 12], ...
    'raan_range_deg', [0 20], ...
    'raan_step_deg', 10, ...
    'plot_visible', 'off', ...
    'artifact_root', artifact_root, ...
    'use_parallel', true, ...
    'min_parallel_rows', 1, ...
    'show_progress', false, ...
    'parallel_monitor', pm);

disp('[manual] Stage05 formal suite smoke completed.');
disp(size(out.legacy_reproduction.grid_table));
disp(size(out.opend_manual_raan.grid_table));
disp(size(out.closedd_manual_raan.grid_table));
disp(out.manifest.manifest_mat);
disp(out.manifest.manifest_txt);
end
