function out = manual_smoke_stage05_passratio_profile_plot()
startup;

raw = run_stage05_opend_legacy_reproduction_framework( ...
    'profile', make_profile_MB_nominal_validation_stage05(), ...
    'i_grid_deg', [30 40 50 60 70 80 90], ...
    'P_grid', [4 6 8 10 12], ...
    'T_grid', [4 6 8 10 12 16], ...
    'h_fixed_km', 1000, ...
    'F_fixed', 1, ...
    'plot_visible', 'off', ...
    'artifact_root', fullfile('outputs','experiments','chapter4','stage05_passratio_profile_plot','raw'), ...
    'output_suffix', 'raw_once', ...
    'use_parallel', true, ...
    'show_progress', false);

products = run_stage05_scan_products( ...
    'preset', 'legacy_stage05_strict', ...
    'artifact_root', fullfile('outputs','experiments','chapter4','stage05_passratio_profile_plot','products'), ...
    'show_progress', false, ...
    'raw_result', raw);

fig = plot_stage05_passratio_profile(products.scan.passratio_profile, ...
    'visible', 'off', ...
    'title', 'Stage05 pass-ratio profile versus Ns');

fig_dir = fullfile('outputs','experiments','chapter4','stage05_passratio_profile_plot','figures');
if exist(fig_dir, 'dir') ~= 7
    mkdir(fig_dir);
end

png_path = save_figure_artifact(fig, struct( ...
    'output_dir', fig_dir, ...
    'file_name', 'stage05_passratio_profile_strict.png'));

out = struct();
out.products = products;
out.png_path = string(png_path);

disp('[manual] Stage05 passratio profile strict plot completed.');
disp(out.png_path);
end
