function products = manual_smoke_stage05_scan_products_from_raw()
startup;

raw = run_stage05_opend_legacy_reproduction_framework( ...
    'profile', make_profile_MB_nominal_validation_stage05(), ...
    'i_grid_deg', [30 40 50 60 70 80 90], ...
    'P_grid', [4 6 8 10 12], ...
    'T_grid', [4 6 8 10 12 16], ...
    'h_fixed_km', 1000, ...
    'F_fixed', 1, ...
    'plot_visible', 'off', ...
    'artifact_root', fullfile('outputs','experiments','chapter4','stage05_scan_products','smoke_raw_reuse','raw'), ...
    'output_suffix', 'raw_once', ...
    'use_parallel', true, ...
    'show_progress', false);

products = run_stage05_scan_products( ...
    'preset', 'legacy_stage05_strict', ...
    'artifact_root', fullfile('outputs','experiments','chapter4','stage05_scan_products','smoke_raw_reuse','products'), ...
    'show_progress', false, ...
    'raw_result', raw);

disp('[manual] Stage05 scan products from injected raw completed.');
disp(size(products.raw.truth_table));
disp(size(products.scan.passratio_profile.value_matrix));
disp(size(products.scan.bestDG_heatmap.value_matrix));
disp(size(products.scan.minNs_heatmap.value_matrix));
end
