function stage15_write_dataset3d_summary(pathStr, dataset)
%STAGE15_WRITE_DATASET3D_SUMMARY  Write minimal 3D dataset summary.

fid = fopen(pathStr, 'w');
assert(fid >= 0, 'Failed to open file: %s', pathStr);
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '=== Stage15-F2 Dataset3D Summary ===\n');
fprintf(fid, 'num_samples = %d\n', numel(dataset));

labels = string({dataset.risk_label});
u = unique(labels, 'stable');

fprintf(fid, '\n--- label histogram ---\n');
for i = 1:numel(u)
    fprintf(fid, '%s = %d\n', u(i), sum(labels == u(i)));
end

fprintf(fid, '\n--- samples ---\n');
fprintf(fid, 'sample_id,r_norm_xy,z_norm,bearing_rad,heading_xy_rad,speed_norm,radial_rate_norm,vertical_rate_norm,rho1_norm,rho2_norm,delta_h1_norm,delta_h2_norm,crossing_angle_deg,lambda_min_geom,rank_proxy,risk_label\n');

for i = 1:numel(dataset)
    d = dataset(i);
    fprintf(fid, '%s,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%d,%s\n', ...
        d.sample_id, ...
        d.xi.r_norm_xy, ...
        d.xi.z_norm, ...
        d.xi.bearing_rad, ...
        d.xi.heading_xy_rad, ...
        d.xi.speed_norm, ...
        d.eta.radial_rate_norm, ...
        d.eta.vertical_rate_norm, ...
        d.kappa2.rho1_norm, ...
        d.kappa2.rho2_norm, ...
        d.kappa2.delta_h1_norm, ...
        d.kappa2.delta_h2_norm, ...
        d.kappa2.crossing_angle_deg, ...
        d.kappa2.lambda_min_geom, ...
        d.kappa2.rank_proxy, ...
        d.risk_label);
end
end
