function d = stage15_compute_template_distance_3d(sample_rec, template_rec)
%STAGE15_COMPUTE_TEMPLATE_DISTANCE_3D
% Weighted distance between one 3D sample and one conditioned template.

xi_s = [
    sample_rec.xi.r_norm_xy, ...
    sample_rec.xi.z_norm, ...
    sample_rec.xi.bearing_rad, ...
    sample_rec.xi.heading_xy_rad, ...
    sample_rec.xi.speed_norm];

xi_t = [
    template_rec.xi_proto.r_norm_xy, ...
    template_rec.xi_proto.z_norm, ...
    template_rec.xi_proto.bearing_rad, ...
    template_rec.xi_proto.heading_xy_rad, ...
    template_rec.xi_proto.speed_norm];

eta_s = [
    sample_rec.eta.radial_rate_norm, ...
    sample_rec.eta.vertical_rate_norm, ...
    sample_rec.eta.turn_proxy];

eta_t = [
    template_rec.eta_proto.radial_rate_norm, ...
    template_rec.eta_proto.vertical_rate_norm, ...
    template_rec.eta_proto.turn_proxy];

k_s = [
    sample_rec.kappa2.rho1_norm, ...
    sample_rec.kappa2.rho2_norm, ...
    sample_rec.kappa2.delta_h1_norm, ...
    sample_rec.kappa2.delta_h2_norm, ...
    sample_rec.kappa2.crossing_angle_deg / 180.0, ...
    sample_rec.kappa2.lambda_min_geom];

k_t = [
    template_rec.kappa2_proto.rho1_norm, ...
    template_rec.kappa2_proto.rho2_norm, ...
    template_rec.kappa2_proto.delta_h1_norm, ...
    template_rec.kappa2_proto.delta_h2_norm, ...
    template_rec.kappa2_proto.crossing_angle_deg / 180.0, ...
    template_rec.kappa2_proto.lambda_min_geom];

w_xi = 0.35;
w_eta = 0.15;
w_k = 0.50;

d = w_xi * sum((xi_s - xi_t).^2) + ...
    w_eta * sum((eta_s - eta_t).^2) + ...
    w_k * sum((k_s - k_t).^2);
end
