function d = stage15_compute_template_distance(sample_rec, template_rec)
%STAGE15_COMPUTE_TEMPLATE_DISTANCE
% Minimal weighted distance between one sample and one template.

xi_s = [
    sample_rec.xi.r_norm, ...
    sample_rec.xi.bearing_rad, ...
    sample_rec.xi.heading_rad, ...
    sample_rec.xi.speed_norm];

xi_t = [
    template_rec.xi_proto.r_norm, ...
    template_rec.xi_proto.bearing_rad, ...
    template_rec.xi_proto.heading_rad, ...
    template_rec.xi_proto.speed_norm];

k_s = [
    sample_rec.kappa2.rho1_norm, ...
    sample_rec.kappa2.rho2_norm, ...
    sample_rec.kappa2.crossing_angle_deg / 180.0, ...
    sample_rec.kappa2.lambda_min_geom];

k_t = [
    template_rec.kappa2_proto.rho1_norm, ...
    template_rec.kappa2_proto.rho2_norm, ...
    template_rec.kappa2_proto.crossing_angle_deg / 180.0, ...
    template_rec.kappa2_proto.lambda_min_geom];

w_xi = 0.4;
w_k = 0.6;

d = w_xi * sum((xi_s - xi_t).^2) + ...
    w_k  * sum((k_s - k_t).^2);
end
