function stage15_write_validation_summary_3d(pathStr, result)
%STAGE15_WRITE_VALIDATION_SUMMARY_3D

fid = fopen(pathStr, 'w');
assert(fid >= 0, 'Failed to open file: %s', pathStr);
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '=== Stage15-G Template Validation Summary ===\n');
fprintf(fid, 'num_samples = %d\n', result.num_samples);
fprintf(fid, 'num_correct = %d\n', result.num_correct);
fprintf(fid, 'accuracy = %.6f\n', result.accuracy);

fprintf(fid, '\n--- matches (first 40) ---\n');
fprintf(fid, 'sample_id,true_geometry,true_layout,true_label,matched_template_id,matched_geometry,matched_layout,matched_label,distance,is_correct\n');

nshow = min(40, numel(result.matches));
for i = 1:nshow
    m = result.matches(i);
    fprintf(fid, '%s,%s,%s,%s,%s,%s,%s,%s,%.6f,%d\n', ...
        m.sample_id, ...
        m.true_geometry_class, ...
        m.true_layout_class, ...
        m.true_label, ...
        m.matched_template_id, ...
        m.matched_geometry_class, ...
        m.matched_layout_class, ...
        m.matched_label, ...
        m.distance, ...
        m.is_correct);
end
end
