function modes = mb_modes(mode_name)
%MB_MODES Registry for MB semantic comparison modes.

registry = local_registry();

if nargin < 1 || isempty(mode_name)
    modes = registry;
    return;
end

token = lower(strtrim(char(string(mode_name))));
if strcmp(token, 'all')
    modes = registry;
    return;
end

names = {registry.name};
match = strcmp(names, token);
if ~any(match)
    error('Unknown MB semantic mode: %s', string(mode_name));
end

modes = registry(match);
end

function registry = local_registry()
registry = [ ...
    local_mode( ...
        'legacydg', ...
        'legacyDG baseline', ...
        'Stage05-style exploratory geometry semantics driven by D_G and legacy pass-ratio aggregation.', ...
        'legacyDG', ...
        true, ...
        false, ...
        false), ...
    local_mode( ...
        'closedd', ...
        'closedD baseline', ...
        'Stage09-compatible closed-D semantics driven by joint feasibility and D-series closure checks.', ...
        'closedD', ...
        false, ...
        true, ...
        false), ...
    local_mode( ...
        'comparison', ...
        'semantic gap comparison', ...
        'Direct semantic comparison between legacyDG and closedD on the same design grid and task family.', ...
        'comparison', ...
        true, ...
        true, ...
        true)];
end

function mode = local_mode(name, label, description, output_tag, uses_legacydg, uses_closedd, emits_gap_outputs)
mode = struct();
mode.name = char(name);
mode.label = string(label);
mode.description = string(description);
mode.output_tag = char(output_tag);
mode.uses_legacydg = logical(uses_legacydg);
mode.uses_closedd = logical(uses_closedd);
mode.emits_gap_outputs = logical(emits_gap_outputs);
end
