function catalog = mb_search_profile_catalog(cfg)
%MB_SEARCH_PROFILE_CATALOG Catalog of named MB search profiles.

if nargin < 1 || isempty(cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(cfg);
end

base = mb_search_profile_defaults(cfg);
stage05_ref = local_stage05_reference(cfg);

profiles = repmat(base, 4, 1);

profiles(1) = local_patch(base, struct( ...
    'name', "mb_default", ...
    'description', "Default MB semantic-comparison profile for routine baseline runs."));

profiles(2) = local_patch(base, struct( ...
    'name', "mb_dense_local", ...
    'description', "Dense local semantic zoom around the semantic shell neighborhood.", ...
    'semantic_mode', "comparison", ...
    'sensor_group_names', {{'baseline'}}, ...
    'height_grid_km', stage05_ref.default_local_heights, ...
    'inclination_grid_deg', cfg.milestones.MB_semantic_compare.dense_local_i_deg, ...
    'P_grid', cfg.milestones.MB_semantic_compare.dense_local_P, ...
    'T_grid', cfg.milestones.MB_semantic_compare.dense_local_T, ...
    'cache', local_patch(base.cache, struct('tag', "mb_dense_local")), ...
    'dense_local', local_patch(base.dense_local, struct( ...
        'enabled', true, ...
        'sensor_group_names', {{'baseline'}}, ...
        'height_grid_km', stage05_ref.default_local_heights))));

profiles(3) = local_patch(base, struct( ...
    'name', "mb_stage05_strict_replica", ...
    'description', "Strict Stage05 replica profile: Stage05 search domain, Stage05-style semantics, and Stage05 sensor defaults.", ...
    'semantic_mode', "legacyDG", ...
    'sensor_group_names', {{'stage05_strict_reference'}}, ...
    'height_grid_km', reshape(stage05_ref.height_grid_km, 1, []), ...
    'inclination_grid_deg', reshape(stage05_ref.inclination_grid_deg, 1, []), ...
    'P_grid', reshape(stage05_ref.P_grid, 1, []), ...
    'T_grid', reshape(stage05_ref.T_grid, 1, []), ...
    'plot_xlim_ns', stage05_ref.plot_xlim_ns, ...
    'cache', local_patch(base.cache, struct('tag', "mb_stage05_strict_replica")), ...
    'stage05_replica', struct( ...
        'strict', true, ...
        'use_stage05_plot_semantics', true, ...
        'use_stage05_search_domain', true, ...
        'use_stage05_sensor_defaults', true)));

profiles(4) = local_patch(base, struct( ...
    'name', "mb_auto_plot_tune", ...
    'description', "Auto-tune candidate profile for pass-ratio plotting range exploration.", ...
    'semantic_mode', "legacyDG", ...
    'sensor_group_names', {{'baseline'}}, ...
    'cache', local_patch(base.cache, struct('tag', "mb_auto_plot_tune")), ...
    'auto_tune', local_patch(base.auto_tune, struct('enabled', true))));

catalog = profiles;
end

function stage05_ref = local_stage05_reference(cfg)
stage05_ref = struct();
stage05_ref.height_grid_km = cfg.stage05.h_fixed_km;
stage05_ref.inclination_grid_deg = cfg.stage05.i_grid_deg;
stage05_ref.P_grid = cfg.stage05.P_grid;
stage05_ref.T_grid = cfg.stage05.T_grid;
stage05_ref.plot_xlim_ns = [min(cfg.stage05.P_grid .* min(cfg.stage05.T_grid)), max(cfg.stage05.P_grid .* max(cfg.stage05.T_grid))];
stage05_ref.default_local_heights = [800, 850, 900, 950, 1000, 1050];
end

function out = local_patch(base, override)
out = milestone_common_merge_structs(base, override);
end
