function profile = mb_search_profile_defaults(cfg)
%MB_SEARCH_PROFILE_DEFAULTS Default MB search-profile scaffold.

if nargin < 1 || isempty(cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(cfg);
end

meta = cfg.milestones.MB_semantic_compare;

profile = struct();
profile.name = "mb_default";
profile.description = "Default MB semantic-compare search profile.";
profile.semantic_mode = "comparison";
profile.sensor_group_names = {'baseline'};
profile.height_grid_km = reshape(meta.heights_to_run, 1, []);
profile.inclination_grid_deg = reshape(meta.i_grid_deg, 1, []);
profile.P_grid = reshape(meta.P_grid, 1, []);
profile.T_grid = reshape(meta.T_grid, 1, []);
profile.P_values = reshape(profile.P_grid, 1, []);
profile.T_values = reshape(profile.T_grid, 1, []);
profile.plot_xlim_ns = [];
profile.Ns_xlim_plot = [];
profile.Ns_target_window = [];
profile.plot_ylim_passratio = [0, 1.05];
profile.plot_xlim_heatmap_P = [min(profile.P_grid), max(profile.P_grid)];
profile.plot_ylim_heatmap_i = [min(profile.inclination_grid_deg), max(profile.inclination_grid_deg)];
profile.plot_xlim_frontier_i = [min(profile.inclination_grid_deg), max(profile.inclination_grid_deg)];
profile.plot_xlim_hi = [min(profile.height_grid_km), max(profile.height_grid_km)];
profile.plot_ylim_hi = [min(profile.inclination_grid_deg), max(profile.inclination_grid_deg)];
profile.auto_tune = struct( ...
    'enabled', false, ...
    'max_iterations', 5, ...
    'max_candidate_count', 12, ...
    'target_transition_center', 0.50, ...
    'required_low_margin', 0.10, ...
    'required_high_margin', 0.10, ...
    'require_left_zero', true, ...
    'require_right_one', true, ...
    'require_mid_transition', true, ...
    'right_plateau_tol', 0.95, ...
    'left_floor_tol', 0.05, ...
    'expand_step_P', 2, ...
    'expand_step_T', 4, ...
    'max_P', 16, ...
    'max_T', 24);
profile.figure_family_overrides = struct();
profile.semantic_overrides = struct();
profile.height_overrides = struct();
profile.sensor_group_overrides = struct();
profile.strict_replica_override = struct();
profile.auto_tune_recommendation = struct();
profile.cli_manual_override = struct();
profile.cache = struct( ...
    'enable', true, ...
    'tag', "mb_default", ...
    'reuse_truth', true, ...
    'reuse_semantic_eval', true, ...
    'reuse_plotting', true, ...
    'reuse_tune_cache', true);
profile.stage05_replica = struct( ...
    'strict', false, ...
    'use_stage05_plot_semantics', false, ...
    'use_stage05_search_domain', false, ...
    'use_stage05_sensor_defaults', false);
profile.dense_local = struct( ...
    'enabled', false, ...
    'sensor_group_names', {{'baseline'}}, ...
    'height_grid_km', reshape(meta.dense_local_heights, 1, []), ...
    'anchor_h_km', meta.dense_local_anchor_h_km, ...
    'inclination_grid_deg', reshape(meta.dense_local_i_deg, 1, []), ...
    'P_grid', reshape(meta.dense_local_P, 1, []), ...
    'T_grid', reshape(meta.dense_local_T, 1, []));
profile.metadata = struct( ...
    'profile_source', "mb_search_profile_defaults", ...
    'created_from', "milestone_common_defaults", ...
    'override_sources', {{'default'}}, ...
    'context', struct());
end
