function catalog = mb_search_profile_catalog(cfg)
%MB_SEARCH_PROFILE_CATALOG Catalog of named MB search profiles.

if nargin < 1 || isempty(cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(cfg);
end

base = mb_search_profile_defaults(cfg);
stage05_ref = local_stage05_reference(cfg);
strict_profile = build_stage05_strict_replica_profile(cfg);

profiles = repmat(base, 4, 1);

profiles(1) = local_patch(base, struct( ...
    'name', "mb_default", ...
    'description', "Default MB semantic-comparison profile for routine baseline runs."));

profiles(2) = local_patch(base, struct( ...
    'name', "mb_dense_local", ...
    'description', "Dense local semantic zoom around the semantic shell neighborhood.", ...
    'semantic_mode', "comparison", ...
    'sensor_group_names', {{'baseline'}}, ...
    'height_grid_km', stage05_ref.default_local_heights, ...
    'inclination_grid_deg', cfg.milestones.MB_semantic_compare.dense_local_i_deg, ...
    'P_grid', cfg.milestones.MB_semantic_compare.dense_local_P, ...
    'T_grid', cfg.milestones.MB_semantic_compare.dense_local_T, ...
    'cache', local_patch(base.cache, struct('tag', "mb_dense_local")), ...
    'dense_local', local_patch(base.dense_local, struct( ...
        'enabled', true, ...
        'sensor_group_names', {{'baseline'}}, ...
        'height_grid_km', stage05_ref.default_local_heights))));

profiles(3) = strict_profile;

profiles(4) = local_patch(base, struct( ...
    'name', "mb_auto_plot_tune", ...
    'description', "Auto-tune candidate profile for pass-ratio plotting range exploration.", ...
    'semantic_mode', "legacyDG", ...
    'sensor_group_names', {{'baseline'}}, ...
    'cache', local_patch(base.cache, struct('tag', "mb_auto_plot_tune")), ...
    'auto_tune', local_patch(base.auto_tune, struct('enabled', true))));

catalog = profiles;
end

function stage05_ref = local_stage05_reference(cfg)
refs = load_stage05_reference_defaults(cfg);
stage05_ref = struct();
stage05_ref.height_grid_km = refs.height_grid_km;
stage05_ref.inclination_grid_deg = refs.inclination_grid_deg;
stage05_ref.P_grid = refs.P_grid;
stage05_ref.T_grid = refs.T_grid;
stage05_ref.plot_xlim_ns = refs.plot_xlim_ns;
stage05_ref.default_local_heights = [800, 850, 900, 950, 1000, 1050];
end

function out = local_patch(base, override)
out = milestone_common_merge_structs(base, override);
end
