function catalog = mb_search_profile_catalog(cfg)
%MB_SEARCH_PROFILE_CATALOG Catalog of named MB search profiles.

if nargin < 1 || isempty(cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(cfg);
end

base = mb_search_profile_defaults(cfg);
stage05_ref = local_stage05_reference(cfg);
strict_profile = build_stage05_strict_replica_profile(cfg);

profiles = repmat(base, 6, 1);

profiles(1) = local_patch(base, struct( ...
    'name', "mb_default", ...
    'description', "Default MB semantic-comparison profile for routine baseline runs.", ...
    'profile_mode', "expand_default", ...
    'profile_mode_description', "incremental Ns expansion up to 400 with a balanced runtime budget", ...
    'cache', local_patch(base.cache, struct('tag', "mb_default"))));

profiles(2) = local_patch(base, struct( ...
    'name', "mb_dense_local", ...
    'description', "Dense local semantic zoom around the semantic shell neighborhood.", ...
    'profile_mode', "expand_default", ...
    'profile_mode_description', "incremental Ns expansion up to 400 with a balanced runtime budget", ...
    'semantic_mode', "comparison", ...
    'sensor_group_names', {{'baseline'}}, ...
    'height_grid_km', stage05_ref.default_local_heights, ...
    'inclination_grid_deg', cfg.milestones.MB_semantic_compare.dense_local_i_deg, ...
    'P_grid', cfg.milestones.MB_semantic_compare.dense_local_P, ...
    'T_grid', cfg.milestones.MB_semantic_compare.dense_local_T, ...
    'cache', local_patch(base.cache, struct('tag', "mb_dense_local")), ...
    'dense_local', local_patch(base.dense_local, struct( ...
        'enabled', true, ...
        'sensor_group_names', {{'baseline'}}, ...
        'height_grid_km', stage05_ref.default_local_heights))));

profiles(3) = strict_profile;

profiles(4) = local_patch(base, struct( ...
    'name', "mb_auto_plot_tune", ...
    'description', "Auto-tune candidate profile for pass-ratio plotting range exploration.", ...
    'profile_mode', "paper", ...
    'profile_mode_description', "prefer 0->1 saturation and centered transition", ...
    'semantic_mode', "legacyDG", ...
    'sensor_group_names', {{'baseline'}}, ...
    'cache', local_patch(base.cache, struct('tag', "mb_auto_plot_tune")), ...
    'auto_tune', local_patch(base.auto_tune, struct('enabled', true))));

heavy_blocks = local_make_expand_blocks({ ...
    struct('name', "heavy_block1", 'ns_min', 248, 'ns_step', 8, 'ns_max', 400), ...
    struct('name', "heavy_block2", 'ns_min', 408, 'ns_step', 8, 'ns_max', 600)});

profiles(5) = local_patch(base, struct( ...
    'name', "mb_heavy", ...
    'description', "Heavy MB semantic-comparison profile with larger incremental Ns coverage.", ...
    'profile_mode', "expand_heavy", ...
    'profile_mode_description', "incremental Ns expansion up to 600 with a larger runtime budget", ...
    'Ns_initial_range', [16, 8, 240], ...
    'Ns_expand_blocks', heavy_blocks, ...
    'Ns_hard_max', 600, ...
    'Ns_allow_expand', true, ...
    'solve_domain_mode', "expandable", ...
    'cache', local_patch(base.cache, struct('tag', "mb_heavy")), ...
    'search_domain', local_patch(base.search_domain, struct( ...
        'Ns_initial_range', [16, 8, 240], ...
        'Ns_expand_blocks', heavy_blocks, ...
        'Ns_hard_max', 600, ...
        'Ns_allow_expand', true, ...
        'solve_domain_mode', "expandable", ...
        'expand_strategy', "incremental_blocks", ...
        'allow_auto_expand_upper', true, ...
        'max_expand_iterations', numel(heavy_blocks))), ...
    'auto_tune', local_patch(base.auto_tune, struct( ...
        'enabled', true, ...
        'max_iterations', max(base.auto_tune.max_iterations, 7), ...
        'max_candidate_count', max(base.auto_tune.max_candidate_count, 16), ...
        'max_P', max(base.auto_tune.max_P, 18), ...
        'max_T', max(base.auto_tune.max_T, 28)))));

fullnight_blocks = local_make_expand_blocks({ ...
    struct('name', "fullnight_block1", 'ns_min', 248, 'ns_step', 8, 'ns_max', 400), ...
    struct('name', "fullnight_block2", 'ns_min', 408, 'ns_step', 8, 'ns_max', 600), ...
    struct('name', "fullnight_block3", 'ns_min', 608, 'ns_step', 8, 'ns_max', 800)});

profiles(6) = local_patch(base, struct( ...
    'name', "mb_final_repair_fullnight", ...
    'description', "Final-repair fullnight MB profile: full fresh recomputation across 500/750/1000 km with complete export regeneration.", ...
    'profile_mode', "final_repair_fullnight", ...
    'profile_mode_description', "full fresh multi-height overnight repair run with complete cache/export regeneration", ...
    'semantic_mode', "comparison", ...
    'sensor_group_names', {{'baseline'}}, ...
    'height_grid_km', [500, 750, 1000], ...
    'Ns_initial_range', [16, 4, 192], ...
    'Ns_expand_blocks', fullnight_blocks, ...
    'Ns_hard_max', 800, ...
    'search_domain', local_patch(base.search_domain, struct( ...
        'policy_name', "mb_final_repair_fullnight", ...
        'height_grid_km', [500, 750, 1000], ...
        'Ns_initial_range', [16, 4, 192], ...
        'Ns_expand_blocks', fullnight_blocks, ...
        'Ns_hard_max', 800, ...
        'Ns_allow_expand', true, ...
        'solve_domain_mode', "expandable", ...
        'expand_strategy', "incremental_blocks", ...
        'expand_stop_policy', local_patch(base.search_domain.expand_stop_policy, struct( ...
            'time_budget_s', 28800, ...
            'max_rounds_without_improvement', 3)), ...
        'allow_auto_expand_upper', true, ...
        'max_expand_iterations', numel(fullnight_blocks))), ...
    'cache', local_patch(base.cache, struct( ...
        'tag', "mb_final_repair_fullnight", ...
        'enable', true, ...
        'reuse_truth', true, ...
        'reuse_semantic', false, ...
        'reuse_plot', false, ...
        'reuse_semantic_eval', false, ...
        'reuse_plotting', false, ...
        'reuse_tune_cache', false, ...
        'force_fresh', true, ...
        'rebuild_all', true)), ...
    'runtime', local_patch(base.runtime, struct( ...
        'force_fresh', true, ...
        'regenerate_all_cache', true, ...
        'regenerate_all_export', true, ...
        'profile_name', "mb_final_repair_fullnight"))));

catalog = profiles;
end

function stage05_ref = local_stage05_reference(cfg)
refs = load_stage05_reference_defaults(cfg);
stage05_ref = struct();
stage05_ref.height_grid_km = refs.height_grid_km;
stage05_ref.inclination_grid_deg = refs.inclination_grid_deg;
stage05_ref.P_grid = refs.P_grid;
stage05_ref.T_grid = refs.T_grid;
stage05_ref.plot_xlim_ns = refs.plot_xlim_ns;
stage05_ref.default_local_heights = [800, 850, 900, 950, 1000, 1050];
end

function out = local_patch(base, override)
out = milestone_common_merge_structs(base, override);
end

function blocks = local_make_expand_blocks(specs)
blocks = repmat(struct('name', "", 'ns_min', NaN, 'ns_step', NaN, 'ns_max', NaN, 'ns_values', []), 1, numel(specs));
for idx = 1:numel(specs)
    spec = specs{idx};
    blocks(idx).name = string(spec.name);
    blocks(idx).ns_min = spec.ns_min;
    blocks(idx).ns_step = spec.ns_step;
    blocks(idx).ns_max = spec.ns_max;
    blocks(idx).ns_values = spec.ns_min:spec.ns_step:spec.ns_max;
end
end
