function profile = mb_search_profile_defaults(cfg)
%MB_SEARCH_PROFILE_DEFAULTS Default MB search-profile scaffold.

if nargin < 1 || isempty(cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(cfg);
end

meta = cfg.milestones.MB_semantic_compare;

profile = struct();
profile.name = "mb_default";
profile.description = "Default MB semantic-compare search profile.";
profile.profile_mode = "expand_default";
profile.profile_mode_description = "incremental Ns expansion up to 400 with a balanced runtime budget";
profile.semantic_mode = "comparison";
profile.sensor_group_names = {'baseline'};
profile.height_grid_km = reshape(meta.heights_to_run, 1, []);
profile.inclination_grid_deg = reshape(meta.i_grid_deg, 1, []);
profile.P_grid = reshape(meta.P_grid, 1, []);
profile.T_grid = reshape(meta.T_grid, 1, []);
profile.P_values = reshape(profile.P_grid, 1, []);
profile.T_values = reshape(profile.T_grid, 1, []);
profile.Ns_initial_range = local_default_ns_initial_range(meta);
profile.Ns_expand_blocks = local_default_ns_expand_blocks('default');
profile.Ns_hard_max = 400;
profile.Ns_allow_expand = true;
profile.solve_domain_mode = "expandable";
profile.expand_strategy = "incremental_blocks";
profile.expand_trigger_policy = struct( ...
    'require_right_unity', true, ...
    'required_upper_target', 0.99, ...
    'end_slope_tol', 0.01, ...
    'boundary_hit_ratio_threshold', 0.25, ...
    'allow_summary_warning_trigger', true);
profile.expand_stop_policy = struct( ...
    'max_rounds_without_improvement', 2, ...
    'min_passratio_gain', 0.01, ...
    'min_frontier_gain', 1, ...
    'time_budget_s', 1800, ...
    'stop_if_two_rounds_without_new_feasible', true);
profile.plot_xlim_ns = [];
profile.Ns_xlim_plot = [];
profile.Ns_target_window = [];
profile.plot_ylim_passratio = [0, 1.05];
profile.plot_xlim_heatmap_P = [min(profile.P_grid), max(profile.P_grid)];
profile.plot_ylim_heatmap_i = [min(profile.inclination_grid_deg), max(profile.inclination_grid_deg)];
profile.plot_xlim_frontier_i = [min(profile.inclination_grid_deg), max(profile.inclination_grid_deg)];
profile.plot_xlim_hi = [min(profile.height_grid_km), max(profile.height_grid_km)];
profile.plot_ylim_hi = [min(profile.inclination_grid_deg), max(profile.inclination_grid_deg)];
profile.search_domain = struct( ...
    'policy_name', "profile_default", ...
    'height_grid_km', reshape(profile.height_grid_km, 1, []), ...
    'inclination_grid_deg', reshape(profile.inclination_grid_deg, 1, []), ...
    'P_grid', reshape(profile.P_grid, 1, []), ...
    'T_grid', reshape(profile.T_grid, 1, []), ...
    'Ns_initial_range', reshape(profile.Ns_initial_range, 1, []), ...
    'Ns_expand_blocks', profile.Ns_expand_blocks, ...
    'Ns_hard_max', profile.Ns_hard_max, ...
    'Ns_allow_expand', profile.Ns_allow_expand, ...
    'solve_domain_mode', profile.solve_domain_mode, ...
    'expand_strategy', profile.expand_strategy, ...
    'expand_trigger_policy', profile.expand_trigger_policy, ...
    'expand_stop_policy', profile.expand_stop_policy, ...
    'heatmap_overcompute', local_getfield_or(meta, 'heatmap_overcompute', struct('mode', 'light')), ...
    'allow_auto_expand_upper', profile.Ns_allow_expand, ...
    'allow_lower_bound_expansion', false, ...
    'max_expand_iterations', numel(profile.Ns_expand_blocks));
profile.plot_domain = struct( ...
    'plot_xlim_mode', "data_range", ...
    'plot_xlim_ns', reshape(profile.Ns_xlim_plot, 1, []), ...
    'plot_ylim_passratio', reshape(profile.plot_ylim_passratio, 1, []), ...
    'plot_ylim_dg', [], ...
    'plot_domain_guardrail_mode', "standard", ...
    'show_domain_annotation', true);
profile.auto_tune = struct( ...
    'enabled', false, ...
    'max_iterations', 5, ...
    'max_candidate_count', 12, ...
    'target_transition_center', 0.50, ...
    'required_low_margin', 0.10, ...
    'required_high_margin', 0.10, ...
    'require_left_zero', true, ...
    'require_right_one', true, ...
    'require_mid_transition', true, ...
    'right_plateau_tol', 0.95, ...
    'left_floor_tol', 0.05, ...
    'expand_step_P', 2, ...
    'expand_step_T', 4, ...
    'max_P', 16, ...
    'max_T', 24);
profile.figure_family_overrides = struct();
profile.semantic_overrides = struct();
profile.height_overrides = struct();
profile.sensor_group_overrides = struct();
profile.strict_replica_override = struct();
profile.auto_tune_recommendation = struct();
profile.cli_manual_override = struct();
profile.cache = struct( ...
    'enable', true, ...
    'tag', "mb_default", ...
    'reuse_truth', true, ...
    'reuse_semantic', false, ...
    'reuse_plot', false, ...
    'reuse_semantic_eval', false, ...
    'reuse_plotting', false, ...
    'reuse_tune_cache', false, ...
    'force_fresh', true, ...
    'rebuild_all', true);
profile.runtime = struct( ...
    'force_fresh', true, ...
    'regenerate_all_cache', true, ...
    'regenerate_all_export', true, ...
    'profile_name', "mb_default");
profile.stage05_replica = struct( ...
    'strict', false, ...
    'use_stage05_plot_semantics', false, ...
    'use_stage05_search_domain', false, ...
    'use_stage05_sensor_defaults', false);
profile.dense_local = struct( ...
    'enabled', false, ...
    'sensor_group_names', {{'baseline'}}, ...
    'height_grid_km', reshape(meta.dense_local_heights, 1, []), ...
    'anchor_h_km', meta.dense_local_anchor_h_km, ...
    'inclination_grid_deg', reshape(meta.dense_local_i_deg, 1, []), ...
    'P_grid', reshape(meta.dense_local_P, 1, []), ...
    'T_grid', reshape(meta.dense_local_T, 1, []));
profile.metadata = struct( ...
    'profile_source', "mb_search_profile_defaults", ...
    'profile_mode', profile.profile_mode, ...
    'profile_mode_description', profile.profile_mode_description, ...
    'created_from', "milestone_common_defaults", ...
    'override_sources', {{'default'}}, ...
    'context', struct());
end

function ns_range = local_default_ns_initial_range(meta)
P_grid = reshape(local_getfield_or(meta, 'P_grid', [4, 6, 8, 10, 12]), 1, []);
T_grid = reshape(local_getfield_or(meta, 'T_grid', [4, 6, 8, 10, 12, 16]), 1, []);
ns_min = min(P_grid) * min(T_grid);
ns_max = max(P_grid) * max(T_grid);
ns_range = [ns_min, 4, ns_max];
end

function blocks = local_default_ns_expand_blocks(mode_name)
switch lower(char(string(mode_name)))
    case 'heavy'
        blocks = [ ...
            local_make_expand_block(248, 8, 400, "heavy_block1"), ...
            local_make_expand_block(408, 8, 600, "heavy_block2")];
    otherwise
        blocks = [ ...
            local_make_expand_block(196, 4, 320, "default_block1"), ...
            local_make_expand_block(324, 4, 400, "default_block2")];
end
end

function block = local_make_expand_block(ns_min, ns_step, ns_max, block_name)
block = struct( ...
    'name', string(block_name), ...
    'ns_min', ns_min, ...
    'ns_step', ns_step, ...
    'ns_max', ns_max, ...
    'ns_values', reshape(ns_min:ns_step:ns_max, 1, []));
end

function value = local_getfield_or(S, field_name, fallback)
if isstruct(S) && isfield(S, field_name)
    value = S.(field_name);
else
    value = fallback;
end
end
