function cfg = milestone_common_defaults(base_cfg, overrides)
%MILESTONE_COMMON_DEFAULTS Build shared milestone configuration.

if nargin < 1 || isempty(base_cfg)
    cfg = default_params();
else
    cfg = base_cfg;
end
if nargin < 2 || isempty(overrides)
    overrides = struct();
end

root_dir = cfg.paths.root;

cfg.paths.output = fullfile(root_dir, 'output');
cfg.paths.milestones = fullfile(root_dir, 'output', 'milestones');

cfg.milestones = struct();
cfg.milestones.output_root = cfg.paths.milestones;
cfg.milestones.save_figures = true;
cfg.milestones.save_tables = true;
cfg.milestones.save_reports = true;
cfg.milestones.overwrite = true;
cfg.milestones.report_timestamp = datestr(now, 'yyyy-mm-dd HH:MM:SS');
cfg.milestones.baseline_case_id = "nominal_01";
cfg.milestones.baseline_theta = struct('h_km', 1000, 'i_deg', 60, 'P', 8, 'T', 4, 'F', 0);
cfg.milestones.Tw_baseline = 60;
cfg.milestones.Tw_list = [30, 60, 90, 120];
cfg.milestones.slice_settings = struct( ...
    'h_km', [800, 1000, 1200], ...
    'i_deg', [40, 60, 80], ...
    'P', [4, 6, 8], ...
    'T', [4, 6, 8], ...
    'target_family', ["nominal", "heading", "critical"], ...
    'sensor_condition', "default");
cfg.milestones.fft_benchmark_sizes = [64, 128, 256, 512];
cfg.milestones.diagnosis_case_id = "critical_01";
cfg.milestones.diagnosis_theta = struct('h_km', 1000, 'i_deg', 60, 'P', 8, 'T', 4, 'F', 0);
cfg.milestones.case_set = "default";

cfg.milestones.MA = struct( ...
    'milestone_id', 'MA', ...
    'title', 'truth_baseline', ...
    'reuse_stages', {{'stage04_window_worstcase', 'stage09_validate_single_design'}}, ...
    'case_id', cfg.milestones.baseline_case_id, ...
    'theta', cfg.milestones.baseline_theta, ...
    'Tw_s', cfg.milestones.Tw_baseline);

cfg.milestones.MB = struct( ...
    'milestone_id', 'MB', ...
    'title', 'inverse_slices', ...
    'reuse_stages', {{'stage05_nominal_walker_search', 'stage06_heading_walker_search', 'stage08_scan_smallgrid_search', 'stage09_build_feasible_domain', 'stage09_extract_minimum_boundary'}}, ...
    'slice_axes', {{'h', 'i', 'P', 'T'}}, ...
    'slice_settings', cfg.milestones.slice_settings);

cfg.milestones.MC = struct( ...
    'milestone_id', 'MC', ...
    'title', 'window_scale', ...
    'reuse_stages', {{'stage08_boundary_window_sensitivity', 'stage09_validate_window_kernel', 'stage09_validate_single_design'}}, ...
    'Tw_list', cfg.milestones.Tw_list, ...
    'theta', cfg.milestones.baseline_theta);

cfg.milestones.MD = struct( ...
    'milestone_id', 'MD', ...
    'title', 'fft_support', ...
    'reuse_stages', {{'stage10A_truth_structure_diagnostics', 'stage10B_build_bcirc_reference', 'stage10C_fft_spectral_validation', 'stage10D_symmetry_breaking_margin', 'stage10E_screening_acceleration'}}, ...
    'benchmark_sizes', cfg.milestones.fft_benchmark_sizes, ...
    'theta', cfg.milestones.baseline_theta);

cfg.milestones.ME = struct( ...
    'milestone_id', 'ME', ...
    'title', 'worst_window_diagnosis', ...
    'reuse_stages', {{'stage10A_truth_structure_diagnostics', 'stage11_entry'}}, ...
    'case_id', cfg.milestones.diagnosis_case_id, ...
    'theta', cfg.milestones.diagnosis_theta);

cfg = milestone_common_merge_structs(cfg, overrides);
end
