function cfg = milestone_common_defaults(base_cfg, overrides)
%MILESTONE_COMMON_DEFAULTS Build shared milestone configuration.

if nargin < 1 || isempty(base_cfg)
    cfg = default_params();
    incoming_milestones = struct();
    incoming_shared_scenarios = struct();
else
    cfg = base_cfg;
    if isfield(base_cfg, 'milestones') && isstruct(base_cfg.milestones)
        incoming_milestones = base_cfg.milestones;
    else
        incoming_milestones = struct();
    end
    if isfield(base_cfg, 'shared_scenarios') && isstruct(base_cfg.shared_scenarios)
        incoming_shared_scenarios = base_cfg.shared_scenarios;
    else
        incoming_shared_scenarios = struct();
    end
end
if nargin < 2 || isempty(overrides)
    overrides = struct();
end

if ~isfield(cfg, 'runtime') || ~isstruct(cfg.runtime)
    cfg.runtime = struct();
end
if ~isfield(cfg.runtime, 'figure_visibility_mode') || isempty(cfg.runtime.figure_visibility_mode)
    cfg.runtime.figure_visibility_mode = 'headless';
end
if ~isfield(cfg.runtime, 'plotting') || ~isstruct(cfg.runtime.plotting)
    cfg.runtime.plotting = struct();
end
cfg.runtime.plotting = milestone_common_merge_structs(struct( ...
    'mode', 'headless', ...
    'default_visible', false, ...
    'close_after_save', true, ...
    'reuse_figures', false, ...
    'export_dpi', 200, ...
    'renderer', 'auto'), cfg.runtime.plotting);
if ~isfield(cfg.runtime, 'parallel') || ~isstruct(cfg.runtime.parallel)
    cfg.runtime.parallel = struct();
end
cfg.runtime.parallel = milestone_common_merge_structs(struct( ...
    'enable', false, ...
    'max_workers', 4, ...
    'mode', 'serial', ...
    'scope', 'none'), cfg.runtime.parallel);
if ~isfield(cfg.runtime, 'force_fresh') || isempty(cfg.runtime.force_fresh)
    cfg.runtime.force_fresh = true;
end
if ~isfield(cfg.runtime, 'regenerate_all_cache') || isempty(cfg.runtime.regenerate_all_cache)
    cfg.runtime.regenerate_all_cache = true;
end
if ~isfield(cfg.runtime, 'regenerate_all_export') || isempty(cfg.runtime.regenerate_all_export)
    cfg.runtime.regenerate_all_export = true;
end
if ~isfield(cfg, 'parallel') || ~isstruct(cfg.parallel)
    cfg.parallel = struct();
end
cfg.parallel = milestone_common_merge_structs(cfg.runtime.parallel, cfg.parallel);
if ~isfield(cfg, 'cache') || ~isstruct(cfg.cache)
    cfg.cache = struct();
end
cfg.cache = milestone_common_merge_structs(struct( ...
    'force_fresh', logical(cfg.runtime.force_fresh), ...
    'reuse_semantic', false, ...
    'reuse_plot', false, ...
    'reuse_truth', true, ...
    'rebuild_all', true), cfg.cache);
if ~isfield(cfg, 'plot_manager') || ~isstruct(cfg.plot_manager)
    cfg.plot_manager = struct();
end
cfg.plot_manager = milestone_common_merge_structs(struct( ...
    'enable', true, ...
    'visible', false, ...
    'default_renderer', 'auto', ...
    'close_after_export', true, ...
    'reuse_existing', false, ...
    'export_dpi', cfg.runtime.plotting.export_dpi), cfg.plot_manager);

root_dir = cfg.paths.root;

cfg.paths.outputs = fullfile(root_dir, 'outputs');
cfg.paths.output = cfg.paths.outputs;
cfg.paths.milestones = fullfile(cfg.paths.outputs, 'milestones');
cfg.paths.shared_scenarios = fullfile(cfg.paths.outputs, 'shared_scenarios');
cfg.paths.stage13 = fullfile(cfg.paths.outputs, 'stage13');
cfg.paths.milestone_outputs = cfg.paths.milestones;
cfg.paths.shared_scenario_outputs = cfg.paths.shared_scenarios;
cfg.paths.stage13_outputs = cfg.paths.stage13;

cfg.milestones = struct();
cfg.milestones.output_root = cfg.paths.milestones;
cfg.milestones.save_figures = true;
cfg.milestones.save_tables = true;
cfg.milestones.save_reports = true;
cfg.milestones.overwrite = true;
cfg.milestones.report_timestamp = datestr(now, 'yyyy-mm-dd HH:MM:SS');
cfg.milestones.baseline_case_mode = 'first_nominal';
cfg.milestones.baseline_case_id = '';
cfg.milestones.baseline_case_label = 'Baseline nominal case';
cfg.milestones.baseline_theta = struct('h_km', 1000, 'i_deg', 60, 'P', 8, 'T', 4, 'F', 0);
cfg.milestones.Tw_baseline = 60;
cfg.milestones.Tw_list = [30, 60, 90, 120];
cfg.milestones.slice_settings = struct( ...
    'h_km', [800, 1000, 1200], ...
    'i_deg', [40, 60, 80], ...
    'P', [4, 6, 8], ...
    'T', [4, 6, 8], ...
    'heading_subset_max', 10, ...
    'target_family', ["nominal", "heading", "critical"], ...
    'sensor_condition', "default");
cfg.milestones.fft_benchmark_sizes = [64, 128, 256, 512];
cfg.milestones.diagnosis_case_mode = 'first_critical';
cfg.milestones.diagnosis_case_id = '';
cfg.milestones.diagnosis_case_label = 'Diagnosis critical case';
cfg.milestones.diagnosis_theta = struct('h_km', 1000, 'i_deg', 60, 'P', 8, 'T', 4, 'F', 0);
cfg.milestones.case_set = "default";

cfg.shared_scenarios = struct();
cfg.shared_scenarios.enable_auto_build = true;
cfg.shared_scenarios.scenario_id = 'baseline_ch4_ch5';
cfg.shared_scenarios.output_root = cfg.paths.shared_scenarios;

cfg.milestones.MA = struct( ...
    'milestone_id', 'MA', ...
    'title', 'truth_baseline', ...
    'reuse_stages', {{'stage12A_truth_baseline_kernel', 'stage12B_truth_case_window_scan'}}, ...
    'case_mode', cfg.milestones.baseline_case_mode, ...
    'case_id', cfg.milestones.baseline_case_id, ...
    'case_label', cfg.milestones.baseline_case_label, ...
    'theta', cfg.milestones.baseline_theta, ...
    'Tw_s', cfg.milestones.Tw_baseline, ...
    'attach_shared_scenarios', true);

% Paper-facing slice ranges for Chapter 4.3.4-4.3.5 thesis views.
cfg.milestones.MB = struct( ...
    'milestone_id', 'MB', ...
    'title', 'inverse_slices', ...
    'reuse_stages', {{'stage12B_mb_design_pool', 'stage12C_inverse_slice_packager', 'stage12D_task_slice_packager', 'stage12E_minimum_design_packager', 'stage12H_mb_near_optimal_shell_check', 'stage12J_mb_fixed_h_exploration'}}, ...
    'slice_axes', {{'h', 'i', 'P', 'T'}}, ...
    'preflight_mode', false, ...
    'fast_mode', false, ...
    'fast_mode_disable_checkpoint', true, ...
    'export_extended_outputs', true, ...
    'export_supplementary_figures', true, ...
    'enable_fixed_h_exploration', true, ...
    'enable_local_dense_zoom', true, ...
    'enable_stage05_passratio_replica', true, ...
    'enable_stage05_semantic_reproduction', true, ...
    'dense_refinement_enabled', true, ...
    'dense_include_hi', true, ...
    'fixed_h_exploration_h_km', [500, 750, 1000], ...
    'fixed_h_exploration_i_deg', [30, 40, 50, 60, 70, 80, 90], ...
    'fixed_h_exploration_P', [4, 6, 8, 10, 12], ...
    'fixed_h_exploration_T', [4, 6, 8, 10, 12, 16], ...
    'fixed_h_exploration_F', 1, ...
    'stage05_semantic_h_km', 500, ...
    'stage05_semantic_i_deg', [30, 40, 50, 60, 70, 80, 90], ...
    'stage05_semantic_P', [4, 6, 8, 10, 12], ...
    'stage05_semantic_T', [4, 6, 8, 10, 12, 16], ...
    'stage05_semantic_F', 1, ...
    'stage05_semantic_use_parallel', true, ...
    'stage05_semantic_force_rebuild_inputs', false, ...
    'fast_heading_subset_max', 6, ...
    'fast_local_block', true, ...
    'fast_local_block_h_km', [800, 900], ...
    'fast_local_block_i_deg', [50, 60], ...
    'fast_local_block_P', [6, 8], ...
    'fast_local_block_T', [6, 8], ...
    'dense_requirement_h_km', [800, 850, 900, 950, 1000, 1050], ...
    'dense_requirement_i_deg', 50:5:70, ...
    'dense_requirement_P', 6:10, ...
    'dense_requirement_T', [6, 8, 10, 12], ...
    'dense_phasecurve_h_km', [800, 900, 1000], ...
    'dense_phasecurve_i_deg', [50, 60, 70], ...
    'dense_phasecurve_P', 4:12, ...
    'dense_phasecurve_T', 4:16, ...
    'slice_settings', struct( ...
        'h_km', [800, 900, 1000, 1100, 1200], ...
        'i_deg', [40, 50, 60, 70, 80], ...
        'P', [4, 6, 8, 10], ...
        'T', [4, 6, 8, 10, 12], ...
        'heading_subset_max', cfg.milestones.slice_settings.heading_subset_max, ...
        'target_family', cfg.milestones.slice_settings.target_family, ...
        'sensor_condition', cfg.milestones.slice_settings.sensor_condition), ...
    'task_slice_settings', struct( ...
        'h_km', [800, 900, 1000], ...
        'i_deg', [50, 60, 70], ...
        'P', [6, 8, 10], ...
        'T', [6, 8, 10, 12], ...
        'heading_subset_max', cfg.milestones.slice_settings.heading_subset_max, ...
        'target_family', cfg.milestones.slice_settings.target_family, ...
        'sensor_condition', cfg.milestones.slice_settings.sensor_condition));

cfg.milestones.MB_semantic_compare = struct( ...
    'milestone_id', 'MB', ...
    'title', 'semantic_compare', ...
    'search_profile', 'mb_default', ...
    'search_profile_mode', 'expand_default', ...
    'search_profile_applied', false, ...
    'enable_search_profile_manager', true, ...
    'mode', 'comparison', ...
    'sensor_groups', {{'baseline'}}, ...
    'family_set', {{'nominal'}}, ...
    'heights_to_run', [500, 750, 1000], ...
    'i_grid_deg', cfg.milestones.MB.fixed_h_exploration_i_deg, ...
    'P_grid', cfg.milestones.MB.fixed_h_exploration_P, ...
    'T_grid', cfg.milestones.MB.fixed_h_exploration_T, ...
    'F_fixed', 1, ...
    'use_parallel', true, ...
    'parallel_policy', 'off', ...
    'max_workers_outer', 4, ...
    'max_workers_inner', 4, ...
    'allow_nested_parallel', false, ...
    'parallel_pool_profile', 'local', ...
    'parallel_partition_strategy', 'inclination', ...
    'fast_mode', false, ...
    'dry_run', false, ...
    'resume_checkpoint', false, ...
    'boundary_diagnostics_enabled', true, ...
    'incremental_expansion_enabled', true, ...
    'heatmap_overcompute', struct( ...
        'mode', 'light', ...
        'max_extra_cells', 6, ...
        'max_extra_P_candidates', 1, ...
        'max_extra_i_neighbors', 1, ...
        'max_extra_T_trials', 3, ...
        'max_extra_designs', 96, ...
        'max_overcompute_time_budget_s', 30), ...
    'frontier_refinement', struct( ...
        'mode', 'light', ...
        'max_refined_cells', 6, ...
        'max_extra_P_neighbors', 1, ...
        'max_extra_i_neighbors', 1, ...
        'max_extra_T_trials', 4, ...
        'max_refined_designs', 96, ...
        'max_time_budget_s', 30), ...
    'search_domain', struct(), ...
    'Ns_initial_range', [16, 4, 192], ...
    'Ns_expand_blocks', repmat(struct('name', "", 'ns_min', NaN, 'ns_step', NaN, 'ns_max', NaN, 'ns_values', []), 1, 0), ...
    'Ns_hard_max', 400, ...
    'Ns_allow_expand', true, ...
    'solve_domain_mode', 'expandable', ...
    'expand_strategy', 'incremental_blocks', ...
    'expand_trigger_policy', struct(), ...
    'expand_stop_policy', struct(), ...
    'plot_domain', struct(), ...
    'search_domain_policy', 'profile_default', ...
    'plot_domain_policy', 'data_range', ...
    'figure_style_mode', 'diagnostic', ...
    'export_paper_ready', false, ...
    'force_fresh', logical(cfg.runtime.force_fresh), ...
    'force_rebuild_all_cache', true, ...
    'regenerate_all_cache', logical(cfg.runtime.regenerate_all_cache), ...
    'regenerate_all_export', logical(cfg.runtime.regenerate_all_export), ...
    'runtime_profile_name', 'mb_default', ...
    'plot_xlim_ns', [], ...
    'plot_ylim_passratio', [0, 1.05], ...
    'paper_ready_guardrail', struct( ...
        'max_boundary_hit_ratio', 0.25, ...
        'require_right_unity', true, ...
        'require_internal_frontier', true), ...
    'auto_tune', struct( ...
        'enabled', false, ...
        'mode', "off", ...
        'max_iterations', 5, ...
        'max_candidate_count', 12, ...
        'target_transition_center', 0.50, ...
        'required_low_margin', 0.10, ...
        'required_high_margin', 0.10, ...
        'expand_step_P', 2, ...
        'expand_step_T', 4, ...
        'max_P', 16, ...
        'max_T', 24), ...
    'cache_policy', 'force_fresh', ...
    'cache_profile', struct( ...
        'enable', true, ...
        'tag', "mb_default", ...
        'semantic_version', "mb-semantic-v1", ...
        'figure_version', "mb-figure-v1", ...
        'reuse_truth', true, ...
        'reuse_semantic', false, ...
        'reuse_plot', false, ...
        'reuse_semantic_eval', false, ...
        'reuse_plotting', false, ...
        'reuse_tune_cache', false, ...
        'force_fresh', true, ...
        'rebuild_all', true, ...
        'strict_compatibility', true), ...
    'auto_tune_apply', false, ...
    'auto_tuned_flag', false, ...
    'stage05_replica', struct( ...
        'strict', false, ...
        'validation_only', false), ...
    'run_dense_local', false, ...
    'dense_local_heights', [800, 850, 900, 950, 1000, 1050], ...
    'dense_local_anchor_h_km', 1000, ...
    'dense_local_sensor_groups', {{'baseline'}}, ...
    'dense_local_i_deg', 50:5:70, ...
    'dense_local_P', 6:10, ...
    'dense_local_T', [6, 8, 10, 12]);

cfg.milestones.MB_plotting = struct( ...
    'passratio_primary_mode', 'globalFullReplay', ...
    'comparison_primary_mode', 'globalFullReplay', ...
    'cross_profile_primary_mode', 'globalFullReplay', ...
    'primary_passratio_view', 'globalFullReplay', ...
    'heatmap_primary_value_mode', 'numeric_requirement', ...
    'heatmap_primary_domain_mode', 'globalReplay', ...
    'primary_heatmap_scope', 'globalReplay', ...
    'export_all_passratio_modes', true, ...
    'export_all_passratio_views', true, ...
    'export_all_heatmap_modes', true, ...
    'export_all_heatmap_scopes', true, ...
    'export_history_full', true, ...
    'export_effective_full_range', true, ...
    'export_frontier_zoom', true, ...
    'export_global_full_replay', true, ...
    'canonical_primary_mode', 'globalFullReplay', ...
    'diagnostic_export_full_bundle', true, ...
    'passratio_connect_missing', false, ...
    'passratio_show_scatter_for_isolated', true, ...
    'passratio_break_long_gaps', true, ...
    'passratio_gap_steps_for_break', 1);

cfg.milestones.MB_plot_data = struct( ...
    'force_dense_rebuild', true, ...
    'allow_sparse_projection', false, ...
    'allow_history_zero_padding', false, ...
    'remove_global_trend_mode', true, ...
    'force_global_numeric_heatmap_rebuild', true);

cfg.vgeom = struct( ...
    'enabled', false, ...
    'height_km', 1000, ...
    'sensor_group', 'baseline', ...
    'semantics', {{'closedD', 'legacyDG'}}, ...
    'inclination_deg_list', [50, 60, 70, 80], ...
    'ns_mode', 'frontier_only', ...
    'ns_list_override', [], ...
    'frontier_neighbor_count', 1, ...
    'use_fundamental_domain', true, ...
    'raan_bins', 6, ...
    'phase_bins', 6, ...
    'enable_fine_pass', false, ...
    'raan_bins_fine', 12, ...
    'phase_bins_fine', 12, ...
    'stats_quantiles', [0.25, 0.5], ...
    'compute_min', true, ...
    'compute_mean', true, ...
    'compute_envelope', true, ...
    'reuse_design_pool', true, ...
    'max_designs_per_case', inf, ...
    'output_scene_cloud', true, ...
    'output_scene_median', true, ...
    'output_scene_q25', true, ...
    'output_scene_q25_envelope', true, ...
    'save_scene_eval_table', true, ...
    'save_scene_agg_table', true, ...
    'save_case_summary', true, ...
    'passratio_connect_missing', false, ...
    'passratio_show_scatter_for_isolated', true, ...
    'passratio_break_long_gaps', true, ...
    'passratio_gap_steps_for_break', 1, ...
    'source_summary_mat', "", ...
    'output_root_tag', 'globalfullreplay');

cfg.milestones.MB_vgeom = struct( ...
    'milestone_id', 'MB_vgeom_h1000', ...
    'title', 'geometry_ensemble', ...
    'source_root_tag', 'globalfullreplay', ...
    'summary_report_name', 'MB_vgeom_summary.md', ...
    'summary_mat_name', 'MB_vgeom_summary.mat');

if ~isfield(cfg, 'stage09') || ~isstruct(cfg.stage09)
    cfg.stage09 = struct();
end
if ~isfield(cfg.stage09, 'enable_checkpoint') || isempty(cfg.stage09.enable_checkpoint)
    cfg.stage09.enable_checkpoint = false;
end
if ~isfield(cfg.stage09, 'checkpoint_every_n') || isempty(cfg.stage09.checkpoint_every_n)
    cfg.stage09.checkpoint_every_n = 20;
end
if ~isfield(cfg.stage09, 'resume_from_checkpoint') || isempty(cfg.stage09.resume_from_checkpoint)
    cfg.stage09.resume_from_checkpoint = false;
end
if ~isfield(cfg.stage09, 'checkpoint_dir') || isempty(cfg.stage09.checkpoint_dir)
    cfg.stage09.checkpoint_dir = fullfile(root_dir, 'cache', 'mb_stage09');
end

cfg.milestones.MC = struct( ...
    'milestone_id', 'MC', ...
    'title', 'window_scale', ...
    'reuse_stages', {{'stage08_boundary_window_sensitivity', 'stage09_validate_window_kernel', 'stage09_validate_single_design'}}, ...
    'Tw_list', cfg.milestones.Tw_list, ...
    'theta', cfg.milestones.baseline_theta);

cfg.milestones.MD = struct( ...
    'milestone_id', 'MD', ...
    'title', 'fft_support', ...
    'reuse_stages', {{'stage10A_truth_structure_diagnostics', 'stage10B_build_bcirc_reference', 'stage10C_fft_spectral_validation', 'stage10D_symmetry_breaking_margin', 'stage10E_screening_acceleration'}}, ...
    'benchmark_sizes', cfg.milestones.fft_benchmark_sizes, ...
    'theta', cfg.milestones.baseline_theta);

cfg.milestones.ME = struct( ...
    'milestone_id', 'ME', ...
    'title', 'worst_window_diagnosis', ...
    'reuse_stages', {{'stage10A_truth_structure_diagnostics', 'stage11_entry'}}, ...
    'case_mode', cfg.milestones.diagnosis_case_mode, ...
    'case_id', cfg.milestones.diagnosis_case_id, ...
    'case_label', cfg.milestones.diagnosis_case_label, ...
    'theta', cfg.milestones.diagnosis_theta);

cfg.milestones = milestone_common_merge_structs(cfg.milestones, incoming_milestones);
cfg.shared_scenarios = milestone_common_merge_structs(cfg.shared_scenarios, incoming_shared_scenarios);
cfg = milestone_common_merge_structs(cfg, overrides);
end
