function artifacts = export_mb_semantic_gap_outputs(legacy_output, closed_output, paths, plot_options)
%EXPORT_MB_SEMANTIC_GAP_OUTPUTS Export comparison artifacts between legacyDG and closedD.

if nargin < 4 || isempty(plot_options)
    plot_options = struct();
end

comparison = build_semantic_gap_tables(legacy_output, closed_output);
sensor_group = char(string(comparison.sensor_group));
sensor_label = char(string(comparison.sensor_label));

artifacts = struct();
artifacts.tables = struct();
artifacts.figures = struct();
artifacts.summary = comparison.summary_table;

summary_csv = fullfile(paths.tables, sprintf('MB_comparison_gap_summary_%s.csv', sensor_group));
milestone_common_save_table(comparison.summary_table, summary_csv);
artifacts.tables.summary = string(summary_csv);

for idx = 1:numel(comparison.run_pairs)
    pair = comparison.run_pairs(idx);
    h_label = sprintf('h%d', round(pair.h_km));

    gap_csv = fullfile(paths.tables, sprintf('MB_comparison_gap_heatmap_iP_%s_%s.csv', h_label, sensor_group));
    pass_csv = fullfile(paths.tables, sprintf('MB_comparison_passratio_overlay_%s_%s.csv', h_label, sensor_group));
    pass_history_csv = fullfile(paths.tables, sprintf('MB_comparison_passratio_overlay_historyFull_%s_%s.csv', h_label, sensor_group));
    pass_effective_csv = fullfile(paths.tables, sprintf('MB_comparison_passratio_overlay_effectiveFullRange_%s_%s.csv', h_label, sensor_group));
    pass_zoom_csv = fullfile(paths.tables, sprintf('MB_comparison_passratio_overlay_frontierZoom_%s_%s.csv', h_label, sensor_group));
    pass_padding_csv = fullfile(paths.tables, sprintf('MB_comparison_passratio_overlay_historyPadding_%s_%s.csv', h_label, sensor_group));
    frontier_csv = fullfile(paths.tables, sprintf('MB_comparison_frontier_shift_%s_%s.csv', h_label, sensor_group));
    frontier_diag_csv = fullfile(paths.tables, sprintf('MB_comparison_frontier_diagnostic_%s_%s.csv', h_label, sensor_group));
    summary_context_csv = fullfile(paths.tables, sprintf('MB_comparison_summary_%s_%s.csv', h_label, sensor_group));
    export_grade_csv = fullfile(paths.tables, sprintf('MB_comparison_export_grade_%s_%s.csv', h_label, sensor_group));
    milestone_common_save_table(pair.requirement_gap_table, gap_csv);
    milestone_common_save_table(pair.passratio_gap_table, pass_csv);
    milestone_common_save_table(pair.frontier_gap_table, frontier_csv);
    milestone_common_save_table(pair.frontier_diagnostic_table, frontier_diag_csv);

    diag_artifacts = export_mb_boundary_hit_outputs(struct( ...
        'boundary_hit_table', pair.boundary_hit_table, ...
        'passratio_saturation_table', pair.passratio_saturation_table, ...
        'frontier_truncation_table', pair.frontier_truncation_table), ...
        paths, sprintf('comparison_%s_%s', h_label, sensor_group));

    fig_gap = plot_semantic_gap_heatmap(pair.requirement_gap_table, pair.h_km, sensor_label, struct( ...
        'boundary_hit_table', pair.boundary_hit_table, ...
        'figure_style', local_getfield_or(plot_options, 'figure_style', struct())));
    gap_png = fullfile(paths.figures, sprintf('MB_comparison_gap_heatmap_iP_%s_%s.png', h_label, sensor_group));
    milestone_common_save_figure(fig_gap, gap_png);
    close(fig_gap);

    pass_windows = resolve_mb_passratio_plot_windows(pair.passratio_gap_table, pair.search_domain, struct( ...
        'y_fields', ["max_pass_ratio_legacyDG"; "max_pass_ratio_closedD"]));
    history_view_spec = struct( ...
        'domain_view', "history_full", ...
        'group_fields', {{'h_km', 'family_name', 'i_deg'}}, ...
        'value_fields', {{'max_pass_ratio_legacyDG', 'max_pass_ratio_closedD', 'legacy_present', 'closed_present', 'passratio_gap'}}, ...
        'fill_values', struct('max_pass_ratio_legacyDG', 0, 'max_pass_ratio_closedD', 0, 'legacy_present', false, 'closed_present', false, 'passratio_gap', 0), ...
        'history_fill_mode', "zero", ...
        'history_origin', "initial_ns_min", ...
        'recompute_mode', "comparison_gap", ...
        'figure_name', sprintf('MB_comparison_passratio_overlay_historyFull_%s_%s.png', h_label, sensor_group));
    [pass_history_table, pass_padding_summary, pass_history_meta] = build_mb_passratio_domain_view(pair.passratio_gap_table, pair.search_domain, history_view_spec);
    milestone_common_save_table(pass_history_table, pass_history_csv);
    milestone_common_save_table(pair.passratio_gap_table, pass_effective_csv);
    milestone_common_save_table(pair.passratio_gap_table, pass_zoom_csv);
    milestone_common_save_table(pass_padding_summary, pass_padding_csv);

    fig_pass_history = plot_semantic_gap_passratio_curves(pass_history_table, pair.h_km, sensor_label, struct( ...
        'passratio_saturation_table', pair.passratio_saturation_table, ...
        'boundary_hit_table', pair.boundary_hit_table, ...
        'search_domain_bounds', [pair.search_domain.ns_search_min, pair.search_domain.ns_search_max], ...
        'plot_domain_label', "history_full", ...
        'plot_domain_source', "history_full", ...
        'plot_xlim_ns', pass_windows.history_full, ...
        'runtime', local_getfield_or(plot_options, 'runtime', struct()), ...
        'figure_style', local_getfield_or(plot_options, 'figure_style', struct())));
    pass_history_png = fullfile(paths.figures, sprintf('MB_comparison_passratio_overlay_historyFull_%s_%s.png', h_label, sensor_group));
    milestone_common_save_figure(fig_pass_history, pass_history_png);
    write_mb_plot_domain_sidecar(pass_history_png, "history_full", "initial_search_domain_lower_bound", local_capture_axis_xlim(fig_pass_history), ...
        build_mb_passratio_view_sidecar_fields(fig_pass_history, pass_history_table, pass_history_csv, "history_full", pass_windows.history_full, pass_history_meta, struct( ...
        'figure_family', "comparison_passratio", ...
        'figure_style_mode', string(local_getfield_or(plot_options, 'figure_style_mode', "")), ...
        'expected_domain_behavior', "history_full_from_initial_ns_min_with_zero_padding", ...
        'actual_domain_behavior', "history_full_padded_table")));
    close(fig_pass_history);

    fig_pass_effective = plot_semantic_gap_passratio_curves(pair.passratio_gap_table, pair.h_km, sensor_label, struct( ...
        'passratio_saturation_table', pair.passratio_saturation_table, ...
        'boundary_hit_table', pair.boundary_hit_table, ...
        'search_domain_bounds', [pair.search_domain.ns_search_min, pair.search_domain.ns_search_max], ...
        'plot_domain_label', "effective_full_range", ...
        'plot_domain_source', "effective_full_range", ...
        'plot_xlim_ns', pass_windows.effective_full_range, ...
        'runtime', local_getfield_or(plot_options, 'runtime', struct()), ...
        'figure_style', local_getfield_or(plot_options, 'figure_style', struct())));
    pass_effective_png = fullfile(paths.figures, sprintf('MB_comparison_passratio_overlay_effectiveFullRange_%s_%s.png', h_label, sensor_group));
    milestone_common_save_figure(fig_pass_effective, pass_effective_png);
    write_mb_plot_domain_sidecar(pass_effective_png, "effective_full_range", "effective_search_domain", local_capture_axis_xlim(fig_pass_effective), ...
        build_mb_passratio_view_sidecar_fields(fig_pass_effective, pair.passratio_gap_table, pass_effective_csv, "effective_full_range", pass_windows.effective_full_range, struct(), struct( ...
        'figure_family', "comparison_passratio", ...
        'figure_style_mode', string(local_getfield_or(plot_options, 'figure_style_mode', "")), ...
        'expected_domain_behavior', "effective_domain_only_without_history_padding", ...
        'actual_domain_behavior', "effective_domain_view")));
    pass_alias_png = fullfile(paths.figures, sprintf('MB_comparison_passratio_overlay_fullRange_%s_%s.png', h_label, sensor_group));
    milestone_common_save_figure(fig_pass_effective, pass_alias_png);
    write_mb_plot_domain_sidecar(pass_alias_png, "effective_full_range", "effective_search_domain", local_capture_axis_xlim(fig_pass_effective), ...
        build_mb_passratio_view_sidecar_fields(fig_pass_effective, pair.passratio_gap_table, pass_effective_csv, "effective_full_range", pass_windows.effective_full_range, struct(), struct('figure_family', "comparison_passratio")));
    global_alias_png = fullfile(paths.figures, sprintf('MB_comparison_passratio_overlay_globalTrend_%s_%s.png', h_label, sensor_group));
    milestone_common_save_figure(fig_pass_effective, global_alias_png);
    write_mb_plot_domain_sidecar(global_alias_png, "effective_full_range", "effective_search_domain", local_capture_axis_xlim(fig_pass_effective), ...
        build_mb_passratio_view_sidecar_fields(fig_pass_effective, pair.passratio_gap_table, pass_effective_csv, "effective_full_range", pass_windows.effective_full_range, struct(), struct('figure_family', "comparison_passratio")));
    close(fig_pass_effective);

    fig_pass_zoom = plot_semantic_gap_passratio_curves(pair.passratio_gap_table, pair.h_km, sensor_label, struct( ...
        'passratio_saturation_table', pair.passratio_saturation_table, ...
        'boundary_hit_table', pair.boundary_hit_table, ...
        'search_domain_bounds', [pair.search_domain.ns_search_min, pair.search_domain.ns_search_max], ...
        'plot_domain_label', "frontier_zoom", ...
        'plot_domain_source', "frontier_zoom", ...
        'plot_xlim_ns', pass_windows.frontier_zoom, ...
        'runtime', local_getfield_or(plot_options, 'runtime', struct()), ...
        'figure_style', local_getfield_or(plot_options, 'figure_style', struct())));
    pass_zoom_png = fullfile(paths.figures, sprintf('MB_comparison_passratio_overlay_frontierZoom_%s_%s.png', h_label, sensor_group));
    milestone_common_save_figure(fig_pass_zoom, pass_zoom_png);
    write_mb_plot_domain_sidecar(pass_zoom_png, "frontier_zoom", "frontier_zoom_window", local_capture_axis_xlim(fig_pass_zoom), ...
        build_mb_passratio_view_sidecar_fields(fig_pass_zoom, pair.passratio_gap_table, pass_zoom_csv, "frontier_zoom", pass_windows.frontier_zoom, struct(), struct( ...
        'figure_family', "comparison_passratio", ...
        'expected_domain_behavior', "frontier_zoom_local_window", ...
        'actual_domain_behavior', "frontier_zoom_view")));
    close(fig_pass_zoom);

    fig_frontier = plot_semantic_gap_frontier_shift(pair.frontier_gap_table, pair.h_km, sensor_label, struct( ...
        'frontier_truncation_table', pair.frontier_truncation_table, ...
        'figure_style', local_getfield_or(plot_options, 'figure_style', struct())));
    frontier_png = fullfile(paths.figures, sprintf('MB_comparison_frontier_shift_%s_%s.png', h_label, sensor_group));
    milestone_common_save_figure(fig_frontier, frontier_png);
    close(fig_frontier);
    summary_context = local_summary_context_table(pair, struct( ...
        'history_full_rendered_min_ns', local_pick_x(local_capture_axis_xlim(fig_pass_history), 1), ...
        'effective_full_rendered_min_ns', local_pick_x(local_capture_axis_xlim(fig_pass_effective), 1), ...
        'frontier_zoom_rendered_min_ns', local_pick_x(local_capture_axis_xlim(fig_pass_zoom), 1), ...
        'history_padding_applied', logical(local_getfield_or(pass_history_meta, 'history_padding_applied', false)), ...
        'domain_consistency_pass', logical(local_pick_x(local_capture_axis_xlim(fig_pass_history), 1) <= local_getfield_or(pass_history_meta, 'initial_ns_min', NaN))));
    milestone_common_save_table(summary_context, summary_context_csv);

    artifacts.tables.(matlab.lang.makeValidName(sprintf('gap_heatmap_iP_%s', h_label))) = string(gap_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('passratio_overlay_%s', h_label))) = string(pass_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('passratio_overlay_historyFull_%s', h_label))) = string(pass_history_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('passratio_overlay_effectiveFullRange_%s', h_label))) = string(pass_effective_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('passratio_overlay_frontierZoom_%s', h_label))) = string(pass_zoom_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('passratio_overlay_historyPadding_%s', h_label))) = string(pass_padding_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('frontier_shift_%s', h_label))) = string(frontier_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('frontier_diagnostic_%s', h_label))) = string(frontier_diag_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('summary_%s', h_label))) = string(summary_context_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('export_grade_%s', h_label))) = string(export_grade_csv);
    artifacts.tables.(matlab.lang.makeValidName(sprintf('boundary_hit_%s', h_label))) = diag_artifacts.boundary_hit_csv;
    artifacts.tables.(matlab.lang.makeValidName(sprintf('passratio_saturation_%s', h_label))) = diag_artifacts.passratio_csv;
    artifacts.tables.(matlab.lang.makeValidName(sprintf('frontier_truncation_%s', h_label))) = diag_artifacts.frontier_csv;
    artifacts.figures.(matlab.lang.makeValidName(sprintf('gap_heatmap_iP_%s', h_label))) = string(gap_png);
    artifacts.figures.(matlab.lang.makeValidName(sprintf('passratioHistory_%s', h_label))) = string(pass_history_png);
    artifacts.figures.(matlab.lang.makeValidName(sprintf('passratioEffective_%s', h_label))) = string(pass_effective_png);
    artifacts.figures.(matlab.lang.makeValidName(sprintf('passratioZoom_%s', h_label))) = string(pass_zoom_png);
    artifacts.figures.(matlab.lang.makeValidName(sprintf('frontier_shift_%s', h_label))) = string(frontier_png);

    diagnostics = struct( ...
        'boundary_hit_table', pair.boundary_hit_table, ...
        'passratio_saturation_table', pair.passratio_saturation_table, ...
        'frontier_truncation_table', pair.frontier_truncation_table);
    export_grade_table = local_build_comparison_export_grade(pair, sensor_group, diagnostics, plot_options);
    milestone_common_save_table(export_grade_table, export_grade_csv);
    local_maybe_export_paper_ready(@() plot_semantic_gap_heatmap(pair.requirement_gap_table, pair.h_km, sensor_label, struct( ...
        'boundary_hit_table', pair.boundary_hit_table, ...
        'figure_style', resolve_mb_figure_style_mode('paper_ready'))), ...
        fullfile(paths.figures, sprintf('MB_comparison_gap_heatmap_iP_%s_%s_paperReady.png', h_label, sensor_group)), ...
        "comparison_heatmap", diagnostics, plot_options);
    local_maybe_export_paper_ready(@() plot_semantic_gap_passratio_curves(pair.passratio_gap_table, pair.h_km, sensor_label, struct( ...
        'passratio_saturation_table', pair.passratio_saturation_table, ...
        'boundary_hit_table', pair.boundary_hit_table, ...
        'search_domain_bounds', [pair.search_domain.ns_search_min, pair.search_domain.ns_search_max], ...
        'plot_domain_label', "effective_full_range", ...
        'plot_xlim_ns', pass_windows.effective_full_range, ...
        'runtime', local_getfield_or(plot_options, 'runtime', struct()), ...
        'figure_style', resolve_mb_figure_style_mode('paper_ready'))), ...
        fullfile(paths.figures, sprintf('MB_comparison_passratio_overlay_effectiveFullRange_%s_%s_paperReady.png', h_label, sensor_group)), ...
        "comparison_passratio", diagnostics, plot_options);
    local_maybe_export_paper_ready(@() plot_semantic_gap_frontier_shift(pair.frontier_gap_table, pair.h_km, sensor_label, struct( ...
        'frontier_truncation_table', pair.frontier_truncation_table, ...
        'figure_style', resolve_mb_figure_style_mode('paper_ready'))), ...
        fullfile(paths.figures, sprintf('MB_comparison_frontier_shift_%s_%s_paperReady.png', h_label, sensor_group)), ...
        "comparison_frontier", diagnostics, plot_options);
end
end

function local_maybe_export_paper_ready(builder_fn, file_path, figure_family, diagnostics, plot_options)
if ~logical(local_getfield_or(plot_options, 'export_paper_ready', false))
    return;
end
guard = guard_mb_paper_ready_export(figure_family, diagnostics, local_getfield_or(plot_options, 'paper_ready_guardrail', struct()));
if ~guard.allowed
    warning('MB:PaperReadyGuard', '%s', char(guard.note));
    return;
end
fig = builder_fn();
milestone_common_save_figure(fig, file_path);
close(fig);
end

function value = local_getfield_or(S, field_name, fallback)
if isstruct(S) && isfield(S, field_name)
    value = S.(field_name);
else
    value = fallback;
end
end

function summary_table = local_summary_context_table(pair, extra_fields)
if nargin < 2 || isempty(extra_fields)
    extra_fields = struct();
end
summary_table = struct2table(pair.summary);
summary_table = addvars(summary_table, ...
    repmat(pair.h_km, height(summary_table), 1), ...
    repmat(string(pair.family_name), height(summary_table), 1), ...
    'Before', 1, ...
    'NewVariableNames', {'h_km', 'family_name'});
extra_names = fieldnames(extra_fields);
for idx = 1:numel(extra_names)
    field_name = extra_names{idx};
    value = extra_fields.(field_name);
    if isstring(value) || ischar(value)
        column = repmat(string(value), height(summary_table), 1);
    elseif islogical(value)
        column = repmat(logical(value), height(summary_table), 1);
    else
        column = repmat(double(value), height(summary_table), 1);
    end
    if ismember(field_name, summary_table.Properties.VariableNames)
        summary_table.(field_name) = column;
    else
        summary_table = addvars(summary_table, column, 'After', width(summary_table), 'NewVariableNames', field_name);
    end
end
end

function export_grade_table = local_build_comparison_export_grade(pair, sensor_group, diagnostics, plot_options)
families = ["comparison_heatmap", "comparison_passratio", "comparison_frontier"];
figure_names = ["gap_heatmap", "passratio_overlay", "frontier_shift"];
rows = cell(numel(families), 10);
for idx = 1:numel(families)
    guard = guard_mb_paper_ready_export(families(idx), diagnostics, local_getfield_or(plot_options, 'paper_ready_guardrail', struct()));
    rows(idx, :) = {pair.h_km, string(sensor_group), string(pair.family_name), figure_names(idx), ...
        string(local_export_grade_from_guard(guard)), logical(guard.allowed), string(guard.status), string(guard.note), ...
        logical(local_getfield_or(guard, 'boundary_dominated', false)), logical(local_getfield_or(guard, 'right_unity_reached', false))};
end
export_grade_table = cell2table(rows, 'VariableNames', {'h_km', 'sensor_group', 'family_name', 'figure_family', ...
    'export_grade', 'paper_ready_allowed', 'guard_status', 'note', 'boundary_dominated', 'right_unity_reached'});
export_grade_table.h_km = double(export_grade_table.h_km);
export_grade_table.paper_ready_allowed = logical(export_grade_table.paper_ready_allowed);
export_grade_table.boundary_dominated = logical(export_grade_table.boundary_dominated);
export_grade_table.right_unity_reached = logical(export_grade_table.right_unity_reached);
end

function grade = local_export_grade_from_guard(guard)
if logical(local_getfield_or(guard, 'allowed', false))
    grade = "paper_candidate";
else
    grade = "diagnostic_only";
end
end

function xlim_values = local_capture_axis_xlim(fig)
xlim_values = capture_mb_primary_axes_xlim(fig);
end

function value = local_pick_x(xlim_values, idx_pick)
value = NaN;
if isnumeric(xlim_values) && numel(xlim_values) >= idx_pick && isfinite(xlim_values(idx_pick))
    value = xlim_values(idx_pick);
end
end
