function T = build_stage14_search_grid_legacy_prepivot_20260329(cfg)
% Stage14 legacy archive note:
% This file was renamed in-place on 20260329 after the Stage14 line of work pivoted back to the Stage05-upgraded mainline.
% Keep logic frozen for comparison, reproduction, and later Stage14.4/14.5 reuse.
%BUILD_STAGE14_SEARCH_GRID_LEGACY_PREPIVOT_20260329
% Build Stage14 search grid over (h_fixed, i, P, T, F, RAAN).

h_fixed_km = cfg.stage14.h_fixed_km;
F_fixed = cfg.stage14.F_fixed;
i_grid_deg = cfg.stage14.i_grid_deg(:);
P_grid = cfg.stage14.P_grid(:);
T_grid = cfg.stage14.T_grid(:);
RAAN_scan_deg = cfg.stage14.RAAN_scan_deg(:);

rows = {};

for ii = 1:numel(i_grid_deg)
    for ip = 1:numel(P_grid)
        for it = 1:numel(T_grid)
            for ir = 1:numel(RAAN_scan_deg)
                i_deg = i_grid_deg(ii);
                P = P_grid(ip);
                TperPlane = T_grid(it);
                RAAN_deg = RAAN_scan_deg(ir);
                Ns = P * TperPlane;

                rows(end+1,:) = { ...
                    h_fixed_km, ...
                    i_deg, ...
                    P, ...
                    TperPlane, ...
                    F_fixed, ...
                    RAAN_deg, ...
                    Ns, ...
                    string(cfg.stage14.family_scope), ...
                    string(cfg.stage14.gamma_source), ...
                    NaN, ...        % gamma_req
                    false, ...      % is_evaluated
                    NaN, ...        % lambda_worst_min
                    NaN, ...        % lambda_worst_mean
                    NaN, ...        % D_G_min
                    NaN, ...        % D_G_mean
                    NaN, ...        % pass_ratio
                    false, ...      % feasible_flag
                    NaN, ...        % rank_score
                    NaN, ...        % n_case_evaluated
                    false ...       % failed_early
                    }; %#ok<AGROW>
            end
        end
    end
end

T = cell2table(rows, 'VariableNames', { ...
    'h_km', ...
    'i_deg', ...
    'P', ...
    'T', ...
    'F', ...
    'RAAN_deg', ...
    'Ns', ...
    'family_scope', ...
    'gamma_source', ...
    'gamma_req', ...
    'is_evaluated', ...
    'lambda_worst_min', ...
    'lambda_worst_mean', ...
    'D_G_min', ...
    'D_G_mean', ...
    'pass_ratio', ...
    'feasible_flag', ...
    'rank_score', ...
    'n_case_evaluated', ...
    'failed_early' ...
    });

T.family_scope = string(T.family_scope);
T.gamma_source = string(T.gamma_source);
end

