function T = build_stage05_search_grid(cfg)
    %BUILD_STAGE05_SEARCH_GRID
    % Build search grid over (h_fixed, i, P, T) for nominal-family Walker search.
    
        h_fixed_km = cfg.stage05.h_fixed_km;
        i_grid_deg = cfg.stage05.i_grid_deg(:);
        P_grid = cfg.stage05.P_grid(:);
        T_grid = cfg.stage05.T_grid(:);
    
        rows = {};
    
        for ii = 1:numel(i_grid_deg)
            for ip = 1:numel(P_grid)
                for it = 1:numel(T_grid)
                    i_deg = i_grid_deg(ii);
                    P = P_grid(ip);
                    TperPlane = T_grid(it);
                    Ns = P * TperPlane;
    
                    rows(end+1,:) = { ...
                        h_fixed_km, ...
                        i_deg, ...
                        P, ...
                        TperPlane, ...
                        Ns, ...
                        string(cfg.stage05.family_scope), ...
                        string(cfg.stage05.gamma_source), ...
                        false, ...
                        NaN, ...
                        NaN, ...
                        NaN, ...
                        NaN, ...
                        NaN, ...
                        NaN ...
                        };
                end
            end
        end
    
        T = cell2table(rows, 'VariableNames', { ...
            'h_km', ...
            'i_deg', ...
            'P', ...
            'T', ...
            'Ns', ...
            'family_scope', ...
            'gamma_source', ...
            'is_evaluated', ...
            'lambda_worst_min', ...
            'lambda_worst_mean', ...
            'D_G_min', ...
            'D_G_mean', ...
            'pass_ratio', ...
            'rank_score' ...
            });

            T.family_scope = string(T.family_scope);
            T.gamma_source = string(T.gamma_source);
    end