function override = resolve_mb_search_profile_mode(mode_in, cfg)
%RESOLVE_MB_SEARCH_PROFILE_MODE Resolve MB search-profile mode overrides.

if nargin < 1 || isempty(mode_in)
    mode_in = "debug";
end
if nargin < 2
    cfg = [];
end

base = mb_search_profile_defaults(cfg);
mode_name = lower(strtrim(char(string(mode_in))));

switch mode_name
    case {'', 'debug'}
        override = struct( ...
            'profile_mode', "debug", ...
            'profile_mode_description', "fast validation with smaller budget", ...
            'auto_tune', milestone_common_merge_structs(base.auto_tune, struct( ...
                'max_iterations', min(base.auto_tune.max_iterations, 3), ...
                'max_candidate_count', min(base.auto_tune.max_candidate_count, 8), ...
                'required_low_margin', 0.05, ...
                'required_high_margin', 0.05, ...
                'max_P', min(base.auto_tune.max_P, 14), ...
                'max_T', min(base.auto_tune.max_T, 20))));
    case 'paper'
        override = struct( ...
            'profile_mode', "paper", ...
            'profile_mode_description', "prefer 0->1 saturation and centered transition", ...
            'auto_tune', milestone_common_merge_structs(base.auto_tune, struct( ...
                'max_iterations', max(base.auto_tune.max_iterations, 7), ...
                'max_candidate_count', max(base.auto_tune.max_candidate_count, 16), ...
                'required_low_margin', 0.15, ...
                'required_high_margin', 0.15, ...
                'right_plateau_tol', 0.98, ...
                'left_floor_tol', 0.03, ...
                'max_P', max(base.auto_tune.max_P, 18), ...
                'max_T', max(base.auto_tune.max_T, 28))));
    case {'strict_replica', 'strict'}
        override = build_stage05_strict_replica_profile(cfg);
        override.profile_mode = "strict_replica";
        override.profile_mode_description = "locked Stage05 reference domain";
        override.auto_tune = milestone_common_merge_structs(local_getfield_or(override, 'auto_tune', struct()), struct('enabled', false));
    otherwise
        error('Unknown MB search profile mode: %s', mode_name);
end
end

function value = local_getfield_or(S, field_name, fallback)
if isstruct(S) && isfield(S, field_name)
    value = S.(field_name);
else
    value = fallback;
end
end
