function override = resolve_mb_search_profile_mode(mode_in, cfg)
%RESOLVE_MB_SEARCH_PROFILE_MODE Resolve MB search-profile mode overrides.

if nargin < 1 || isempty(mode_in)
    mode_in = "expand_default";
end
if nargin < 2
    cfg = [];
end

base = mb_search_profile_defaults(cfg);
mode_name = lower(strtrim(char(string(mode_in))));

switch mode_name
    case {'', 'debug', 'expand_default'}
        override = struct( ...
            'profile_mode', "expand_default", ...
            'profile_mode_description', "incremental Ns expansion up to 400 with a balanced runtime budget", ...
            'Ns_initial_range', [16, 4, 192], ...
            'Ns_expand_blocks', local_make_expand_blocks({ ...
                struct('name', "default_block1", 'ns_min', 196, 'ns_step', 4, 'ns_max', 320), ...
                struct('name', "default_block2", 'ns_min', 324, 'ns_step', 4, 'ns_max', 400)}), ...
            'Ns_hard_max', 400, ...
            'Ns_allow_expand', true, ...
            'solve_domain_mode', "expandable", ...
            'expand_strategy', "incremental_blocks", ...
            'search_domain', struct( ...
                'Ns_initial_range', [16, 4, 192], ...
                'Ns_expand_blocks', local_make_expand_blocks({ ...
                    struct('name', "default_block1", 'ns_min', 196, 'ns_step', 4, 'ns_max', 320), ...
                    struct('name', "default_block2", 'ns_min', 324, 'ns_step', 4, 'ns_max', 400)}), ...
                'Ns_hard_max', 400, ...
                'Ns_allow_expand', true, ...
                'solve_domain_mode', "expandable", ...
                'expand_strategy', "incremental_blocks", ...
                'allow_auto_expand_upper', true, ...
                'max_expand_iterations', 2), ...
            'auto_tune', milestone_common_merge_structs(base.auto_tune, struct( ...
                'max_iterations', min(base.auto_tune.max_iterations, 3), ...
                'max_candidate_count', min(base.auto_tune.max_candidate_count, 8), ...
                'required_low_margin', 0.05, ...
                'required_high_margin', 0.05, ...
                'max_P', min(base.auto_tune.max_P, 14), ...
                'max_T', min(base.auto_tune.max_T, 20))));
    case {'expand_heavy', 'heavy'}
        override = struct( ...
            'profile_mode', "expand_heavy", ...
            'profile_mode_description', "incremental Ns expansion up to 600 with a larger runtime budget", ...
            'Ns_initial_range', [16, 8, 240], ...
            'Ns_expand_blocks', local_make_expand_blocks({ ...
                struct('name', "heavy_block1", 'ns_min', 248, 'ns_step', 8, 'ns_max', 400), ...
                struct('name', "heavy_block2", 'ns_min', 408, 'ns_step', 8, 'ns_max', 600)}), ...
            'Ns_hard_max', 600, ...
            'Ns_allow_expand', true, ...
            'solve_domain_mode', "expandable", ...
            'expand_strategy', "incremental_blocks", ...
            'search_domain', struct( ...
                'Ns_initial_range', [16, 8, 240], ...
                'Ns_expand_blocks', local_make_expand_blocks({ ...
                    struct('name', "heavy_block1", 'ns_min', 248, 'ns_step', 8, 'ns_max', 400), ...
                    struct('name', "heavy_block2", 'ns_min', 408, 'ns_step', 8, 'ns_max', 600)}), ...
                'Ns_hard_max', 600, ...
                'Ns_allow_expand', true, ...
                'solve_domain_mode', "expandable", ...
                'expand_strategy', "incremental_blocks", ...
                'allow_auto_expand_upper', true, ...
                'max_expand_iterations', 2), ...
            'auto_tune', milestone_common_merge_structs(base.auto_tune, struct( ...
                'max_iterations', max(base.auto_tune.max_iterations, 7), ...
                'max_candidate_count', max(base.auto_tune.max_candidate_count, 16), ...
                'required_low_margin', 0.15, ...
                'required_high_margin', 0.15, ...
                'max_P', max(base.auto_tune.max_P, 18), ...
                'max_T', max(base.auto_tune.max_T, 28))));
    case 'paper'
        override = struct( ...
            'profile_mode', "paper", ...
            'profile_mode_description', "prefer 0->1 saturation and centered transition", ...
            'auto_tune', milestone_common_merge_structs(base.auto_tune, struct( ...
                'max_iterations', max(base.auto_tune.max_iterations, 7), ...
                'max_candidate_count', max(base.auto_tune.max_candidate_count, 16), ...
                'required_low_margin', 0.15, ...
                'required_high_margin', 0.15, ...
                'right_plateau_tol', 0.98, ...
                'left_floor_tol', 0.03, ...
                'max_P', max(base.auto_tune.max_P, 18), ...
                'max_T', max(base.auto_tune.max_T, 28))));
    case {'strict_replica', 'strict'}
        override = build_stage05_strict_replica_profile(cfg);
        override.profile_mode = "strict_replica";
        override.profile_mode_description = "locked Stage05 reference domain";
        override.auto_tune = milestone_common_merge_structs(local_getfield_or(override, 'auto_tune', struct()), struct('enabled', false));
    otherwise
        error('Unknown MB search profile mode: %s', mode_name);
end
end

function value = local_getfield_or(S, field_name, fallback)
if isstruct(S) && isfield(S, field_name)
    value = S.(field_name);
else
    value = fallback;
end
end

function blocks = local_make_expand_blocks(specs)
blocks = repmat(struct('name', "", 'ns_min', NaN, 'ns_step', NaN, 'ns_max', NaN, 'ns_values', []), 1, numel(specs));
for idx = 1:numel(specs)
    spec = specs{idx};
    blocks(idx).name = string(spec.name);
    blocks(idx).ns_min = spec.ns_min;
    blocks(idx).ns_step = spec.ns_step;
    blocks(idx).ns_max = spec.ns_max;
    blocks(idx).ns_values = spec.ns_min:spec.ns_step:spec.ns_max;
end
end
