function style_mode = resolve_mb_figure_style_mode(mode_in)
%RESOLVE_MB_FIGURE_STYLE_MODE Resolve MB figure export style behavior.

mode_name = lower(strtrim(char(string(mode_in))));
if isempty(mode_name)
    mode_name = 'diagnostic';
end

switch mode_name
    case {'paper', 'paper_ready', 'paperready'}
        style_mode = struct( ...
            'name', "paper_ready", ...
            'show_domain_annotation', false, ...
            'show_diagnostic_annotation', false, ...
            'export_suffix', "_paperReady", ...
            'description', "paper_ready: hide debug annotations and export only when guardrails pass");
    otherwise
        style_mode = struct( ...
            'name', "diagnostic", ...
            'show_domain_annotation', true, ...
            'show_diagnostic_annotation', true, ...
            'export_suffix', "", ...
            'description', "diagnostic: keep search-domain, plot-domain, boundary, and stop-reason annotations visible");
end
end
