function [summary_table, eig_table] = build_stage10D_bound_table(Wtruth, A0, lambda_min_bcirc, specC, eps_pack, meta, cfg)
%BUILD_STAGE10D_BOUND_TABLE
% Build margin / bound summary tables for Stage10.D.
%
% Inputs:
%   Wtruth            : 3x3 truth full matrix
%   A0                : 3x3 zero-mode block
%   lambda_min_bcirc  : scalar, minimum eigenvalue of legal full bcirc
%   specC             : Stage10.C spectral pack
%   eps_pack          : from compute_eps_sb_stage10D
%   meta              : struct with case/theta/window info
%
% Bounds reported:
%   zero-mode bounds:
%       lambda_min(A0) - eps_sb <= lambda_min(Wtruth) <= lambda_min(A0) + eps_sb
%   bcirc-min bounds:
%       lambda_min(W_{r,0}) - eps_sb <= lambda_min(Wtruth) <= lambda_min(W_{r,0}) + eps_sb
%
% Note:
%   zero-mode bound is dimension-consistent and often sharper.
%   bcirc-min bound is kept for comparison, though typically conservative.

    if nargin < 7
        cfg = default_params();
    end
    cfg = stage10D_prepare_cfg(cfg);

    Wtruth = 0.5 * (Wtruth + Wtruth.');
    A0 = 0.5 * (A0 + A0.');

    ev_truth = sort(real(eig(Wtruth)), 'ascend');
    ev_A0 = sort(real(eig(A0)), 'ascend');

    lambda_full = ev_truth(1);
    lambda_zero = ev_A0(1);

    eps2 = eps_pack.eps_sb_2;
    epsF = eps_pack.eps_sb_fro;

    zero_lb = lambda_zero - eps2;
    zero_ub = lambda_zero + eps2;

    bcirc_lb = lambda_min_bcirc - eps2;
    bcirc_ub = lambda_min_bcirc + eps2;

    zero_hit = (lambda_full >= zero_lb) && (lambda_full <= zero_ub);
    bcirc_hit = (lambda_full >= bcirc_lb) && (lambda_full <= bcirc_ub);

    summary_table = table( ...
        string(meta.case_id), string(meta.family), ...
        meta.h_km, meta.i_deg, meta.P_theta, meta.T_theta, meta.F_theta, meta.Ns_theta, ...
        meta.window_index, meta.t0_s, meta.t1_s, ...
        lambda_full, lambda_zero, lambda_min_bcirc, specC.lambda_min_fft, ...
        eps2, epsF, ...
        zero_lb, zero_ub, zero_hit, ...
        bcirc_lb, bcirc_ub, bcirc_hit, ...
        abs(lambda_full - lambda_zero), ...
        abs(lambda_full - lambda_min_bcirc), ...
        abs(lambda_zero - lambda_min_bcirc), ...
        'VariableNames', { ...
            'case_id','family', ...
            'h_km','i_deg','P_theta','T_theta','F_theta','Ns_theta', ...
            'window_index','t0_s','t1_s', ...
            'lambda_full_eff', ...
            'lambda_zero_mode', ...
            'lambda_min_bcirc', ...
            'lambda_min_fft', ...
            'eps_sb_2','eps_sb_fro', ...
            'zero_lb','zero_ub','zero_hit', ...
            'bcirc_lb','bcirc_ub','bcirc_hit', ...
            'gap_full_zero', ...
            'gap_full_bcirc', ...
            'gap_zero_bcirc'});

    eig_table = table( ...
        (1:3).', ev_truth, ev_A0, ...
        'VariableNames', {'eig_index','eig_truth_full','eig_zero_mode'});
end