function [summary_table, confusion_table] = compare_stage10E_screening_vs_truth(scan_table, cfg)
%COMPARE_STAGE10E_SCREENING_VS_TRUTH
% Summarize screening performance against truth pass/fail.

    cfg = stage10E_prepare_cfg(cfg);

    truth = logical(scan_table.truth_pass);
    zero_pred = logical(scan_table.zero_pass);
    two_pred = logical(scan_table.two_stage_pass);
    bcirc_pred = logical(scan_table.bcirc_pass);

    [zero_tp, zero_fp, zero_fn, zero_tn] = local_conf(truth, zero_pred);
    [two_tp, two_fp, two_fn, two_tn] = local_conf(truth, two_pred);
    [bc_tp, bc_fp, bc_fn, bc_tn] = local_conf(truth, bcirc_pred);

    confusion_table = table( ...
        string({'zero_mode'; 'two_stage'; 'bcirc_only'}), ...
        [zero_tp; two_tp; bc_tp], ...
        [zero_fp; two_fp; bc_fp], ...
        [zero_fn; two_fn; bc_fn], ...
        [zero_tn; two_tn; bc_tn], ...
        'VariableNames', {'method','TP','FP','FN','TN'});

    summary_table = table( ...
        height(scan_table), ...
        sum(truth), ...
        sum(~truth), ...
        mean(abs(scan_table.lambda_truth - scan_table.lambda_zero)), ...
        mean(abs(scan_table.lambda_truth - scan_table.lambda_bcirc)), ...
        mean(scan_table.eps_sb_2), ...
        'VariableNames', { ...
            'N_total', ...
            'N_truth_pass', ...
            'N_truth_fail', ...
            'mean_gap_truth_zero', ...
            'mean_gap_truth_bcirc', ...
            'mean_eps_sb_2'});
end


function [tp, fp, fn, tn] = local_conf(truth, pred)
    tp = sum(truth & pred);
    fp = sum(~truth & pred);
    fn = sum(truth & ~pred);
    tn = sum(~truth & ~pred);
end