function cfg = shared_scenario_common_defaults(base_cfg, overrides)
%SHARED_SCENARIO_COMMON_DEFAULTS Build shared scenario illustration config.

if nargin < 1 || isempty(base_cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(base_cfg);
end
if nargin < 2 || isempty(overrides)
    overrides = struct();
end

cfg.paths.shared_scenarios = fullfile(cfg.paths.root, 'output', 'shared_scenarios');

cfg.shared_scenarios = struct();
cfg.shared_scenarios.enable_auto_build = true;
cfg.shared_scenarios.scenario_id = 'baseline_ch4_ch5';
cfg.shared_scenarios.output_root = cfg.paths.shared_scenarios;
cfg.shared_scenarios.start_time = '2026-01-01 00:00:00';
cfg.shared_scenarios.stop_time = '2026-01-01 00:45:00';
cfg.shared_scenarios.sample_time_s = 60;
cfg.shared_scenarios.earth_radius_m = cfg.geo.a_m;
cfg.shared_scenarios.representative_case_ids = ["N01", "H01_+00", "C1"];
cfg.shared_scenarios.baseline_theta = cfg.milestones.baseline_theta;
cfg.shared_scenarios.show_nominal_family = true;
cfg.shared_scenarios.show_heading_family = true;
cfg.shared_scenarios.show_critical_family = true;
cfg.shared_scenarios.zone = struct( ...
    'center_lat_deg', cfg.geo.lat0_deg, ...
    'center_lon_deg', cfg.geo.lon0_deg, ...
    'radius_km', cfg.stage01.R_D_km);
cfg.shared_scenarios.walker = struct( ...
    'altitude_km', cfg.milestones.baseline_theta.h_km, ...
    'inclination_deg', cfg.milestones.baseline_theta.i_deg, ...
    'total_satellites', cfg.milestones.baseline_theta.P * cfg.milestones.baseline_theta.T, ...
    'geometry_planes', cfg.milestones.baseline_theta.P, ...
    'phasing', cfg.milestones.baseline_theta.F, ...
    'raan_offset_deg', 0, ...
    'mean_anomaly_offset_deg', 0);
cfg.shared_scenarios.stk = struct( ...
    'enabled', true, ...
    'visible', false, ...
    'keep_open', false, ...
    'scenario_name', 'SharedWalkerScenario', ...
    'satellite_name_prefix', 'WalkerSat', ...
    'progid_candidates', {{'STKX12.Application', 'STK12.Application', 'STK11.Application'}}, ...
    'coordinate_system', 'J2000', ...
    'propagator', 'TwoBody', ...
    'export_root', fullfile(tempdir, 'codex_stk_exports'), ...
    'mirror_export_root', fullfile(cfg.paths.shared_scenarios, 'stk_exports'));
cfg.shared_scenarios.render = struct( ...
    'max_orbit_planes_to_show', 3, ...
    'max_satellites_per_plane_to_mark', 2, ...
    'show_target_trajectory', true, ...
    'use_tex', true);

cfg.shared_scenarios.SS1 = struct( ...
    'scenario_id', 'SS1', ...
    'title', 'defense_zone_hgv_relationship_2d', ...
    'source', 'stage01_stage02');

cfg.shared_scenarios.SS2 = struct( ...
    'scenario_id', 'SS2', ...
    'title', 'stk_walker_constellation_3d', ...
    'source', 'stk_matlab');

cfg = milestone_common_merge_structs(cfg, overrides);
end
