function T = build_stage06_search_grid(cfg)
    %BUILD_STAGE06_SEARCH_GRID
    % Build search grid over (h_fixed, i, P, T, F) for heading-extended Walker search.
    
        h_fixed_km = cfg.stage06.h_fixed_km;
        F_fixed = cfg.stage06.F_fixed;
        i_grid_deg = cfg.stage06.i_grid_deg(:);
        P_grid = cfg.stage06.P_grid(:);
        T_grid = cfg.stage06.T_grid(:);
    
        rows = {};
    
        for ii = 1:numel(i_grid_deg)
            for ip = 1:numel(P_grid)
                for it = 1:numel(T_grid)
                    i_deg = i_grid_deg(ii);
                    P = P_grid(ip);
                    TperPlane = T_grid(it);
                    Ns = P * TperPlane;
    
                    rows(end+1,:) = { ...
                        h_fixed_km, ...
                        i_deg, ...
                        P, ...
                        TperPlane, ...
                        F_fixed, ...
                        Ns, ...
                        string(cfg.stage06.family_scope), ...
                        string(cfg.stage06.gamma_source), ...
                        NaN, ...        % gamma_req
                        false, ...      % is_evaluated
                        NaN, ...        % lambda_worst_min
                        NaN, ...        % lambda_worst_mean
                        NaN, ...        % D_G_min
                        NaN, ...        % D_G_mean
                        NaN, ...        % pass_ratio
                        false, ...      % feasible_flag
                        NaN ...         % rank_score
                        }; %#ok<AGROW>
                end
            end
        end
    
        T = cell2table(rows, 'VariableNames', { ...
            'h_km', ...
            'i_deg', ...
            'P', ...
            'T', ...
            'F', ...
            'Ns', ...
            'family_scope', ...
            'gamma_source', ...
            'gamma_req', ...
            'is_evaluated', ...
            'lambda_worst_min', ...
            'lambda_worst_mean', ...
            'D_G_min', ...
            'D_G_mean', ...
            'pass_ratio', ...
            'feasible_flag', ...
            'rank_score' ...
            });
    
        T.family_scope = string(T.family_scope);
        T.gamma_source = string(T.gamma_source);
    end