function cfg = stage13_default_config(base_cfg, overrides)
%STAGE13_DEFAULT_CONFIG Build Stage13 baseline neighborhood-search config.

existing_stage13 = struct();
if nargin < 1 || isempty(base_cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(base_cfg);
    if isfield(base_cfg, 'stage13') && isstruct(base_cfg.stage13)
        existing_stage13 = base_cfg.stage13;
    end
end
if nargin < 2 || isempty(overrides)
    overrides = struct();
end

cfg.paths.stage13 = cfg.paths.stage13_outputs;

cfg.stage13 = struct();
cfg.stage13.stage_name = 'stage13';
cfg.stage13.mode = 'baseline_neighborhood';
cfg.stage13.output_root = cfg.paths.stage13;
cfg.stage13.save_tables = true;
cfg.stage13.save_figures = true;
cfg.stage13.save_reports = true;
cfg.stage13.baseline = struct( ...
    'case_mode', 'exact', ...
    'case_id', 'N01', ...
    'case_label', 'MA baseline nominal case', ...
    'Tw_s', 60, ...
    'theta', cfg.milestones.baseline_theta);
cfg.stage13.search = struct( ...
    'families', {{'dt_first_probe', 'dg_first_probe'}}, ...
    'max_candidates_per_family', 7, ...
    'max_representatives_per_family', 3);
cfg.stage13.dg_refine = struct( ...
    'enable', false, ...
    'seed_case', 'dg_first_probe_3', ...
    'micro', struct( ...
        'enable', true, ...
        'entry_theta_offsets_deg', [-1 0 1], ...
        'heading_offset_offsets_deg', [-4 -2 0 2 4]));

cfg.stage13 = milestone_common_merge_structs(cfg.stage13, existing_stage13);
cfg = milestone_common_merge_structs(cfg, overrides);
end
