function out = aggregate_stage14_multi_ns_stats(cfg, filter_opts, ns_list)
%AGGREGATE_STAGE14_MULTI_NS_STATS
% Aggregate Stage14 Ns-envelope stats across multiple Ns values.
%
% Input:
%   cfg
%   filter_opts : struct with fields
%       h_km, i_deg, F, visible, save_fig, save_table
%   ns_list     : vector of Ns values
%
% Output:
%   out.summary_table_all
%   out.per_ns_results

    arguments
        cfg struct
        filter_opts struct
        ns_list (1,:) double
    end

    ns_list = unique(ns_list(:).');
    ns_list = ns_list(isfinite(ns_list));
    assert(~isempty(ns_list), 'ns_list is empty.');

    per_ns_results = cell(numel(ns_list), 1);
    rows = cell(0, 25);

    for k = 1:numel(ns_list)
        Ns = ns_list(k);

        opts = filter_opts;
        opts.Ns = Ns;
        opts.quiet = true;
        opts.visible = "off";
        opts.save_fig = false;

        try
            res = stage14_analyze_ns_envelopes(cfg, opts);
            per_ns_results{k} = res;

            S = res.stats.summary_table;
            rows(end+1,:) = { ...
                S.h_km(1), ...
                S.i_deg(1), ...
                S.F(1), ...
                S.Ns(1), ...
                S.DG_env_mean(1), ...
                S.DG_env_min(1), ...
                S.DG_env_max(1), ...
                S.DG_env_span(1), ...
                S.DG_env_std(1), ...
                S.pass_env_mean(1), ...
                S.pass_env_min(1), ...
                S.pass_env_max(1), ...
                S.pass_env_span(1), ...
                S.pass_env_std(1), ...
                S.best_P_of_raan_mean_DG(1), ...
                S.best_T_of_raan_mean_DG(1), ...
                S.best_P_of_raan_min_DG(1), ...
                S.best_T_of_raan_min_DG(1), ...
                S.RAAN_of_raan_min_DG(1), ...
                S.best_P_of_raan_mean_pass(1), ...
                S.best_T_of_raan_mean_pass(1), ...
                S.best_P_of_raan_min_pass(1), ...
                S.best_T_of_raan_min_pass(1), ...
                S.RAAN_of_raan_min_pass(1), ...
                true ...
                }; %#ok<AGROW>
        catch
            per_ns_results{k} = [];
            rows(end+1,:) = { ...
                filter_opts.h_km, ...
                filter_opts.i_deg, ...
                filter_opts.F, ...
                Ns, ...
                NaN, NaN, NaN, NaN, NaN, ...
                NaN, NaN, NaN, NaN, NaN, ...
                NaN, NaN, NaN, NaN, NaN, ...
                NaN, NaN, NaN, NaN, NaN, ...
                false ...
                }; %#ok<AGROW>
        end
    end

    summary_table_all = cell2table(rows, 'VariableNames', { ...
        'h_km','i_deg','F','Ns', ...
        'DG_env_mean','DG_env_min','DG_env_max','DG_env_span','DG_env_std', ...
        'pass_env_mean','pass_env_min','pass_env_max','pass_env_span','pass_env_std', ...
        'best_P_of_raan_mean_DG','best_T_of_raan_mean_DG', ...
        'best_P_of_raan_min_DG','best_T_of_raan_min_DG','RAAN_of_raan_min_DG', ...
        'best_P_of_raan_mean_pass','best_T_of_raan_mean_pass', ...
        'best_P_of_raan_min_pass','best_T_of_raan_min_pass','RAAN_of_raan_min_pass', ...
        'is_valid' ...
        });

    summary_table_all = sortrows(summary_table_all, 'Ns');

    out = struct();
    out.summary_table_all = summary_table_all;
    out.per_ns_results = per_ns_results;
end
