function [master_table, screening_table] = build_stage10F_master_summary(core, cfg)
%BUILD_STAGE10F_MASTER_SUMMARY
% Build compact thesis-ready summary tables from Stage10 core outputs.

    cfg = stage10F_prepare_cfg(cfg);

    SA = core.outA.summary_table;
    SB = core.outB.summary_table;
    SB1 = core.outB1.summary_table;
    SC = core.outC.summary_table;
    SD = core.outD.summary_table;
    SE1 = core.outE1.summary_table;
    CE1 = core.outE1.confusion_table;
    LE1 = core.outE1.label_count_table;

    master_table = table( ...
        SA.case_id(1), SA.family(1), ...
        SA.h_km(1), SA.i_deg(1), SA.P_theta(1), SA.T_theta(1), SA.F_theta(1), SA.Ns_theta(1), ...
        SA.window_index(1), SA.t0_s(1), SA.t1_s(1), ...
        SA.n_active_plane(1), SA.active_ratio(1), ...
        SA.top1_trace_share(1), SA.top2_trace_share(1), SA.top3_trace_share(1), ...
        SB1.mirror_gap_before(1), SB1.mirror_gap_after(1), ...
        SB1.lambda_min_proto_bcirc(1), SB1.lambda_min_legal_bcirc(1), ...
        SC.lambda_zero_mode(1), SC.lambda_min_bcirc(1), SC.lambda_min_fft(1), ...
        SC.fft_consistency_abs_err(1), ...
        SD.eps_sb_2(1), SD.eps_sb_fro(1), ...
        SD.zero_hit(1), SD.bcirc_hit(1), ...
        SD.gap_full_zero(1), SD.gap_full_bcirc(1), SD.gap_zero_bcirc(1), ...
        'VariableNames', { ...
            'case_id','family', ...
            'h_km','i_deg','P','T','F','Ns', ...
            'window_index','t0_s','t1_s', ...
            'n_active_plane','active_ratio', ...
            'top1_trace_share','top2_trace_share','top3_trace_share', ...
            'mirror_gap_before','mirror_gap_after', ...
            'lambda_min_proto_bcirc','lambda_min_legal_bcirc', ...
            'lambda_zero_mode','lambda_min_bcirc','lambda_min_fft', ...
            'fft_consistency_abs_err', ...
            'eps_sb_2','eps_sb_fro', ...
            'zero_hit','bcirc_hit', ...
            'gap_full_zero','gap_full_bcirc','gap_zero_bcirc'});

    % extract confusion rows
    row_accept = strcmp(CE1.method, "accept_after_refine");
    row_safe = strcmp(CE1.method, "safe_only");

    count_reject = local_get_count(LE1, "reject");
    count_warn = local_get_count(LE1, "warn_pass");
    count_safe = local_get_count(LE1, "safe_pass");

    screening_table = table( ...
        SE1.N_total(1), ...
        SE1.N_truth_pass(1), ...
        SE1.N_truth_fail(1), ...
        count_reject, count_warn, count_safe, ...
        CE1.TP(row_accept), CE1.FP(row_accept), CE1.FN(row_accept), CE1.TN(row_accept), ...
        CE1.TP(row_safe), CE1.FP(row_safe), CE1.FN(row_safe), CE1.TN(row_safe), ...
        SE1.N_truth_pass_warn(1), SE1.N_truth_pass_safe(1), ...
        SE1.N_truth_fail_warn(1), SE1.N_truth_fail_safe(1), ...
        SE1.mean_gap_truth_zero(1), SE1.mean_gap_truth_bcirc(1), SE1.mean_eps_sb_2(1), ...
        'VariableNames', { ...
            'N_total', ...
            'N_truth_pass','N_truth_fail', ...
            'N_reject','N_warn','N_safe', ...
            'TP_accept_after_refine','FP_accept_after_refine','FN_accept_after_refine','TN_accept_after_refine', ...
            'TP_safe_only','FP_safe_only','FN_safe_only','TN_safe_only', ...
            'N_truth_pass_warn','N_truth_pass_safe', ...
            'N_truth_fail_warn','N_truth_fail_safe', ...
            'mean_gap_truth_zero','mean_gap_truth_bcirc','mean_eps_sb_2'});
end


function c = local_get_count(T, label)
    idx = strcmp(T.stage_label, label);
    if any(idx)
        c = T.count(idx);
    else
        c = 0;
    end
end