function profile = build_stage05_strict_replica_profile(cfg)
%BUILD_STAGE05_STRICT_REPLICA_PROFILE Build the strict Stage05 replica search profile.

if nargin < 1 || isempty(cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(cfg);
end

base = mb_search_profile_defaults(cfg);
refs = load_stage05_reference_defaults(cfg);

profile = milestone_common_merge_structs(base, struct( ...
    'name', "mb_stage05_strict_replica", ...
    'description', "Strict Stage05 replica profile driven by centralized Stage05 reference defaults.", ...
    'semantic_mode', "legacyDG", ...
    'sensor_group_names', {{'stage05_strict_reference'}}, ...
    'height_grid_km', refs.height_grid_km, ...
    'inclination_grid_deg', refs.inclination_grid_deg, ...
    'P_grid', refs.P_grid, ...
    'T_grid', refs.T_grid, ...
    'plot_xlim_ns', refs.plot_xlim_ns, ...
    'cache', milestone_common_merge_structs(base.cache, struct('tag', "mb_stage05_strict_replica")), ...
    'stage05_replica', struct( ...
        'strict', true, ...
        'use_stage05_plot_semantics', true, ...
        'use_stage05_search_domain', true, ...
        'use_stage05_sensor_defaults', true), ...
    'metadata', milestone_common_merge_structs(base.metadata, struct( ...
        'profile_source', "build_stage05_strict_replica_profile", ...
        'reference_tag', refs.reference_tag))));
end
