function out = build_stage09_parameter_domain_tables(full_theta_table, feasible_theta_table, boundary_struct)
%BUILD_STAGE09_PARAMETER_DOMAIN_TABLES
% Build human-readable parameter-domain summary tables for Stage09.
%
% Input
%   full_theta_table     : full scan table from Stage09.4
%   feasible_theta_table : feasible subset from Stage09.4
%   boundary_struct      : output of extract_stage09_minimum_boundary
%
% Output fields
%   out.parameter_range_table
%   out.minimum_boundary_table
%   out.theta_min_table_sorted

    if nargin < 3
        error('build_stage09_parameter_domain_tables requires 3 inputs.');
    end
    if ~istable(full_theta_table) || ~istable(feasible_theta_table)
        error('full_theta_table and feasible_theta_table must be tables.');
    end
    if ~isstruct(boundary_struct)
        error('boundary_struct must be a struct.');
    end

    % ------------------------------------------------------------
    % Overall feasible range table
    % ------------------------------------------------------------
    if isempty(feasible_theta_table) || height(feasible_theta_table) < 1
        parameter_range_table = table( ...
            inf, nan, nan, nan, nan, nan, nan, ...
            'VariableNames', { ...
                'Ns_min_feasible', ...
                'h_min_km','h_max_km', ...
                'i_min_deg','i_max_deg', ...
                'P_min','P_max'});
        minimum_boundary_table = boundary_struct.boundary_table;
        theta_min_table_sorted = boundary_struct.theta_min_table;
    else
        parameter_range_table = table( ...
            min(feasible_theta_table.Ns), ...
            min(feasible_theta_table.h_km), ...
            max(feasible_theta_table.h_km), ...
            min(feasible_theta_table.i_deg), ...
            max(feasible_theta_table.i_deg), ...
            min(feasible_theta_table.P), ...
            max(feasible_theta_table.P), ...
            min(feasible_theta_table.T), ...
            max(feasible_theta_table.T), ...
            height(feasible_theta_table), ...
            'VariableNames', { ...
                'Ns_min_feasible', ...
                'h_min_km','h_max_km', ...
                'i_min_deg','i_max_deg', ...
                'P_min','P_max', ...
                'T_min','T_max', ...
                'n_feasible_theta'});

        minimum_boundary_table = boundary_struct.boundary_table;

        theta_min_table_sorted = boundary_struct.theta_min_table;
        if ~isempty(theta_min_table_sorted)
            theta_min_table_sorted = sortrows(theta_min_table_sorted, ...
                {'joint_margin','h_km','i_deg','P','T'}, ...
                {'descend','ascend','ascend','ascend','ascend'});
        end
    end

    out = struct();
    out.parameter_range_table = parameter_range_table;
    out.minimum_boundary_table = minimum_boundary_table;
    out.theta_min_table_sorted = theta_min_table_sorted;
end