function history_table = build_mb_incremental_search_history(history_rows)
%BUILD_MB_INCREMENTAL_SEARCH_HISTORY Convert incremental-search records to a table.

if nargin < 1 || isempty(history_rows)
    history_table = table();
    return;
end
if istable(history_rows)
    history_table = history_rows;
    return;
end

rows = cell(numel(history_rows), 1);
for idx = 1:numel(history_rows)
    row = history_rows(idx);
    rows{idx, 1} = table( ...
        local_getfield_or(row, 'iteration', idx), ...
        string(local_getfield_or(row, 'semantic_mode', "")), ...
        string(local_getfield_or(row, 'sensor_group', "")), ...
        string(local_getfield_or(row, 'family_name', "")), ...
        local_getfield_or(row, 'height_km', NaN), ...
        string(local_getfield_or(row, 'action', "")), ...
        string(local_getfield_or(row, 'stop_reason', "")), ...
        logical(local_getfield_or(row, 'cache_seed_hit', false)), ...
        local_getfield_or(row, 'previous_design_count', 0), ...
        local_getfield_or(row, 'added_design_count', 0), ...
        local_getfield_or(row, 'merged_design_count', 0), ...
        string(mat2str(reshape(local_getfield_or(row, 'P_grid', []), 1, []))), ...
        string(mat2str(reshape(local_getfield_or(row, 'T_grid', []), 1, []))), ...
        local_getfield_or(row, 'ns_search_min', NaN), ...
        local_getfield_or(row, 'ns_search_max', NaN), ...
        'VariableNames', {'iteration', 'semantic_mode', 'sensor_group', 'family_name', 'height_km', ...
        'action', 'stop_reason', 'cache_seed_hit', 'previous_design_count', 'added_design_count', ...
        'merged_design_count', 'P_grid', 'T_grid', 'ns_search_min', 'ns_search_max'});
end
history_table = vertcat(rows{:});
end

function value = local_getfield_or(S, field_name, fallback)
if isstruct(S) && isfield(S, field_name)
    value = S.(field_name);
else
    value = fallback;
end
end
