function profile = build_stage05_strict_replica_profile(cfg)
%BUILD_STAGE05_STRICT_REPLICA_PROFILE Build the strict Stage05 replica search profile.

if nargin < 1 || isempty(cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(cfg);
end

base = mb_search_profile_defaults(cfg);
refs = load_stage05_reference_defaults(cfg);
strict_lock = struct( ...
    'semantic_mode', "legacyDG", ...
    'sensor_group_names', {{'stage05_strict_reference'}}, ...
    'height_grid_km', reshape(refs.height_grid_km, 1, []), ...
    'inclination_grid_deg', reshape(refs.inclination_grid_deg, 1, []), ...
    'P_grid', reshape(refs.P_grid, 1, []), ...
    'T_grid', reshape(refs.T_grid, 1, []), ...
    'P_values', reshape(refs.P_grid, 1, []), ...
    'T_values', reshape(refs.T_grid, 1, []), ...
    'plot_xlim_ns', reshape(refs.plot_xlim_ns, 1, []), ...
    'Ns_xlim_plot', reshape(refs.plot_xlim_ns, 1, []), ...
    'Ns_target_window', reshape(refs.plot_xlim_ns, 1, []), ...
    'stage05_replica', struct( ...
        'strict', true, ...
        'use_stage05_plot_semantics', true, ...
        'use_stage05_search_domain', true, ...
        'use_stage05_sensor_defaults', true));

profile = milestone_common_merge_structs(base, struct( ...
    'name', "strict_stage05_replica", ...
    'description', "Strict Stage05 replica profile driven by centralized Stage05 reference defaults.", ...
    'semantic_mode', strict_lock.semantic_mode, ...
    'sensor_group_names', strict_lock.sensor_group_names, ...
    'height_grid_km', strict_lock.height_grid_km, ...
    'inclination_grid_deg', strict_lock.inclination_grid_deg, ...
    'P_grid', strict_lock.P_grid, ...
    'T_grid', strict_lock.T_grid, ...
    'P_values', strict_lock.P_values, ...
    'T_values', strict_lock.T_values, ...
    'plot_xlim_ns', strict_lock.plot_xlim_ns, ...
    'Ns_xlim_plot', strict_lock.Ns_xlim_plot, ...
    'Ns_target_window', strict_lock.Ns_target_window, ...
    'cache', milestone_common_merge_structs(base.cache, struct('tag', "strict_stage05_replica")), ...
    'figure_family_overrides', struct( ...
        'strict_replica', strict_lock, ...
        'control_stage05', struct( ...
            'plot_xlim_ns', strict_lock.plot_xlim_ns, ...
            'Ns_xlim_plot', strict_lock.Ns_xlim_plot, ...
            'Ns_target_window', strict_lock.Ns_target_window)), ...
    'semantic_overrides', struct( ...
        'legacydg', struct('semantic_mode', "legacyDG")), ...
    'sensor_group_overrides', struct( ...
        'stage05_strict_reference', strict_lock), ...
    'strict_replica_override', strict_lock, ...
    'stage05_replica', strict_lock.stage05_replica, ...
    'metadata', milestone_common_merge_structs(base.metadata, struct( ...
        'profile_source', "build_stage05_strict_replica_profile", ...
        'reference_tag', refs.reference_tag, ...
        'profile_aliases', {{'strict_stage05_replica', 'mb_stage05_strict_replica'}}))));
end
