function [manifest_struct, manifest_table] = build_stage05_strict_replica_manifest(strict_output, validation_meta)
%BUILD_STAGE05_STRICT_REPLICA_MANIFEST Build a one-row manifest for strict replica validation.

if nargin < 1 || isempty(strict_output)
    strict_output = struct();
end
if nargin < 2 || isempty(validation_meta)
    validation_meta = struct();
end

reference_defaults = local_getfield_or(strict_output, 'reference_defaults', struct());
strict_profile = local_getfield_or(strict_output, 'strict_profile', struct());
sensor_group = local_getfield_or(strict_output, 'sensor_group', struct());
summary = local_getfield_or(strict_output, 'summary', struct());

manifest_struct = struct();
manifest_struct.mode = "stage05_strict_replica";
manifest_struct.semantic_mode = string(local_getfield_or(summary, 'semantic_mode', "legacyDG"));
manifest_struct.sensor_group = string(local_getfield_or(sensor_group, 'name', "stage05_strict_reference"));
manifest_struct.search_profile = string(local_getfield_or(summary, 'search_profile', local_getfield_or(strict_profile, 'name', "strict_stage05_replica")));
manifest_struct.plot_style = string(local_getfield_or(summary, 'plot_style', "stage05_replica_style"));
manifest_struct.reference_defaults_tag = string(local_getfield_or(validation_meta, 'reference_defaults_tag', local_getfield_or(reference_defaults, 'reference_tag', "")));
manifest_struct.max_off_boresight_deg = local_getfield_or(sensor_group, 'max_off_boresight_deg', NaN);
manifest_struct.angle_resolution_arcsec = local_getfield_or(sensor_group, 'angle_resolution_arcsec', NaN);
manifest_struct.angle_resolution_rad = local_getfield_or(sensor_group, 'angle_resolution_rad', NaN);
manifest_struct.height_grid_km = reshape(local_getfield_or(strict_profile, 'height_grid_km', local_getfield_or(reference_defaults, 'height_grid_km', [])), 1, []);
manifest_struct.P_grid = reshape(local_getfield_or(strict_profile, 'P_grid', local_getfield_or(reference_defaults, 'P_grid', [])), 1, []);
manifest_struct.T_grid = reshape(local_getfield_or(strict_profile, 'T_grid', local_getfield_or(reference_defaults, 'T_grid', [])), 1, []);
manifest_struct.plot_xlim_ns = reshape(local_getfield_or(strict_profile, 'plot_xlim_ns', local_getfield_or(reference_defaults, 'plot_xlim_ns', [])), 1, []);
manifest_struct.reference_output_file = string(local_getfield_or(validation_meta, 'reference_output_file', ""));
manifest_struct.reference_stage02_file = string(local_getfield_or(validation_meta, 'reference_stage02_file', ""));
manifest_struct.reference_stage04_file = string(local_getfield_or(validation_meta, 'reference_stage04_file', ""));
manifest_struct.reference_table_file = string(local_getfield_or(validation_meta, 'reference_table_file', ""));
manifest_struct.reference_feasible_table_file = string(local_getfield_or(validation_meta, 'reference_feasible_table_file', ""));
manifest_struct.max_abs_diff = local_getfield_or(validation_meta, 'max_abs_diff', NaN);
manifest_struct.max_curve_abs_diff = local_getfield_or(validation_meta, 'max_curve_abs_diff', NaN);
manifest_struct.validation_tol = local_getfield_or(validation_meta, 'validation_tol', NaN);
manifest_struct.validation_pass = logical(local_getfield_or(validation_meta, 'validation_pass', false));
manifest_struct.source_defaults_files = local_getfield_or(reference_defaults, 'source_files', {});
manifest_struct.lock_manifest = local_getfield_or(strict_output, 'lock_manifest', struct());

manifest_table = table( ...
    manifest_struct.semantic_mode, ...
    manifest_struct.sensor_group, ...
    manifest_struct.search_profile, ...
    manifest_struct.plot_style, ...
    manifest_struct.reference_defaults_tag, ...
    manifest_struct.max_off_boresight_deg, ...
    manifest_struct.angle_resolution_arcsec, ...
    manifest_struct.angle_resolution_rad, ...
    string(mat2str(manifest_struct.height_grid_km)), ...
    string(mat2str(manifest_struct.P_grid)), ...
    string(mat2str(manifest_struct.T_grid)), ...
    string(mat2str(manifest_struct.plot_xlim_ns)), ...
    manifest_struct.reference_output_file, ...
    manifest_struct.reference_stage02_file, ...
    manifest_struct.reference_stage04_file, ...
    manifest_struct.reference_table_file, ...
    manifest_struct.reference_feasible_table_file, ...
    manifest_struct.max_abs_diff, ...
    manifest_struct.max_curve_abs_diff, ...
    manifest_struct.validation_tol, ...
    manifest_struct.validation_pass, ...
    string(strjoin(cellstr(string(manifest_struct.source_defaults_files)), '; ')), ...
    string(strjoin(cellstr(manifest_struct.lock_manifest.ignored_option_fields), ', ')), ...
    'VariableNames', { ...
        'semantic_mode', ...
        'sensor_group', ...
        'search_profile', ...
        'plot_style', ...
        'reference_defaults_tag', ...
        'max_off_boresight_deg', ...
        'angle_resolution_arcsec', ...
        'angle_resolution_rad', ...
        'height_grid_km', ...
        'P_grid', ...
        'T_grid', ...
        'plot_xlim_ns', ...
        'reference_output_file', ...
        'reference_stage02_file', ...
        'reference_stage04_file', ...
        'reference_table_file', ...
        'reference_feasible_table_file', ...
        'max_abs_diff', ...
        'max_curve_abs_diff', ...
        'validation_tol', ...
        'validation_pass', ...
        'source_defaults_files', ...
        'ignored_option_fields'});
end

function value = local_getfield_or(S, field_name, fallback)
if isstruct(S) && isfield(S, field_name)
    value = S.(field_name);
else
    value = fallback;
end
end
