function design_table = build_mb_fixed_h_design_table(h_km, i_grid_deg, P_grid, T_grid, F_fixed, slice_source)
%BUILD_MB_FIXED_H_DESIGN_TABLE Build an explicit fixed-height design table for exploratory MB scans.

if nargin < 6 || isempty(slice_source)
    slice_source = "fixed_h_exploration";
end

[I, P, TT] = ndgrid(i_grid_deg(:), P_grid(:), T_grid(:));
n = numel(I);

design_table = table( ...
    repmat(h_km, n, 1), ...
    I(:), ...
    P(:), ...
    TT(:), ...
    repmat(F_fixed, n, 1), ...
    P(:) .* TT(:), ...
    repmat(string(slice_source), n, 1), ...
    'VariableNames', {'h_km', 'i_deg', 'P', 'T', 'F', 'Ns', 'slice_source'});

design_table = unique_design_rows(design_table);
design_table = sortrows(design_table, {'Ns', 'i_deg', 'P', 'T'}, {'ascend', 'ascend', 'ascend', 'ascend'});
end
