function profile = build_stage05_strict_replica_profile(cfg)
%BUILD_STAGE05_STRICT_REPLICA_PROFILE Build the strict Stage05 replica search profile.

if nargin < 1 || isempty(cfg)
    cfg = milestone_common_defaults();
else
    cfg = milestone_common_defaults(cfg);
end

base = mb_search_profile_defaults(cfg);
refs = load_stage05_reference_defaults(cfg);
strict_lock = struct( ...
    'semantic_mode', "legacyDG", ...
    'sensor_group_names', {{'stage05_strict_reference'}}, ...
    'height_grid_km', reshape(refs.height_grid_km, 1, []), ...
    'inclination_grid_deg', reshape(refs.inclination_grid_deg, 1, []), ...
    'P_grid', reshape(refs.P_grid, 1, []), ...
    'T_grid', reshape(refs.T_grid, 1, []), ...
    'P_values', reshape(refs.P_grid, 1, []), ...
    'T_values', reshape(refs.T_grid, 1, []), ...
    'plot_xlim_ns', reshape(refs.plot_xlim_ns, 1, []), ...
    'Ns_xlim_plot', reshape(refs.plot_xlim_ns, 1, []), ...
    'Ns_target_window', reshape(refs.plot_xlim_ns, 1, []), ...
    'Ns_initial_range', [min(refs.plot_xlim_ns), local_estimate_step(refs.plot_xlim_ns), max(refs.plot_xlim_ns)], ...
    'Ns_expand_blocks', repmat(struct('name', "", 'ns_min', NaN, 'ns_step', NaN, 'ns_max', NaN, 'ns_values', []), 1, 0), ...
    'Ns_hard_max', max(refs.plot_xlim_ns), ...
    'Ns_allow_expand', false, ...
    'solve_domain_mode', "fixed", ...
    'expand_strategy', "locked_reference", ...
    'stage05_replica', struct( ...
        'strict', true, ...
        'plot_style', "stage05_replica_style", ...
        'use_stage05_plot_semantics', true, ...
        'use_stage05_search_domain', true, ...
        'use_stage05_sensor_defaults', true));

profile = milestone_common_merge_structs(base, struct( ...
    'name', "strict_stage05_replica", ...
    'description', "Strict Stage05 replica profile driven by centralized Stage05 reference defaults.", ...
    'profile_mode', "strict_replica", ...
    'profile_mode_description', "locked Stage05 reference domain", ...
    'semantic_mode', strict_lock.semantic_mode, ...
    'sensor_group_names', strict_lock.sensor_group_names, ...
    'height_grid_km', strict_lock.height_grid_km, ...
    'inclination_grid_deg', strict_lock.inclination_grid_deg, ...
    'P_grid', strict_lock.P_grid, ...
    'T_grid', strict_lock.T_grid, ...
    'P_values', strict_lock.P_values, ...
    'T_values', strict_lock.T_values, ...
    'plot_xlim_ns', strict_lock.plot_xlim_ns, ...
    'Ns_xlim_plot', strict_lock.Ns_xlim_plot, ...
    'Ns_target_window', strict_lock.Ns_target_window, ...
    'Ns_initial_range', strict_lock.Ns_initial_range, ...
    'Ns_expand_blocks', strict_lock.Ns_expand_blocks, ...
    'Ns_hard_max', strict_lock.Ns_hard_max, ...
    'Ns_allow_expand', strict_lock.Ns_allow_expand, ...
    'solve_domain_mode', strict_lock.solve_domain_mode, ...
    'expand_strategy', strict_lock.expand_strategy, ...
    'cache', milestone_common_merge_structs(base.cache, struct('tag', "strict_stage05_replica")), ...
    'figure_family_overrides', struct( ...
        'strict_replica', strict_lock, ...
        'control_stage05', struct( ...
            'plot_xlim_ns', strict_lock.plot_xlim_ns, ...
            'Ns_xlim_plot', strict_lock.Ns_xlim_plot, ...
            'Ns_target_window', strict_lock.Ns_target_window)), ...
    'semantic_overrides', struct( ...
        'legacydg', struct('semantic_mode', "legacyDG")), ...
    'sensor_group_overrides', struct( ...
        'stage05_strict_reference', strict_lock), ...
    'strict_replica_override', strict_lock, ...
    'stage05_replica', strict_lock.stage05_replica, ...
    'metadata', milestone_common_merge_structs(base.metadata, struct( ...
        'profile_source', "build_stage05_strict_replica_profile", ...
        'profile_mode', "strict_replica", ...
        'profile_mode_description', "locked Stage05 reference domain", ...
        'reference_tag', refs.reference_tag, ...
        'plot_style', "stage05_replica_style", ...
        'profile_aliases', {{'strict_stage05_replica', 'mb_stage05_strict_replica'}}))));
end

function step = local_estimate_step(values)
values = unique(reshape(values, 1, []));
if numel(values) < 2
    step = NaN;
    return;
end
diffs = diff(values);
diffs = diffs(diffs > 0);
if isempty(diffs)
    step = NaN;
else
    step = diffs(1);
end
end
