function fig = plot_mb_frontier_vs_i(frontier_table, style)
%PLOT_MB_FRONTIER_VS_I Plot the minimum-feasible constellation frontier as a function of inclination.

if nargin < 2 || isempty(style)
    style = milestone_common_plot_style();
end

fig = figure('Visible', 'off', 'Color', 'w');
ax = axes(fig);
hold(ax, 'on');

if isempty(frontier_table)
    apply_mb_plot_domain_guardrail(ax, [], [], struct( ...
        'empty_message', 'No valid frontier points in current search domain', ...
        'domain_summary', 'Frontier summary is empty for the current search domain', ...
        'plot_domain_source', "no_valid_frontier"));
else
    valid_mask = isfinite(frontier_table.i_deg) & isfinite(frontier_table.minimum_feasible_Ns);
    frontier_table = frontier_table(valid_mask, :);
    if isempty(frontier_table)
        apply_mb_plot_domain_guardrail(ax, [], [], struct( ...
            'empty_message', 'No valid frontier points in current search domain', ...
            'domain_summary', 'Frontier rows exist but contain no finite point', ...
            'plot_domain_source', "no_valid_frontier"));
    elseif numel(unique(frontier_table.i_deg)) < 2
        plot(ax, frontier_table.i_deg, frontier_table.minimum_feasible_Ns, 'o', ...
            'Color', style.colors(1, :), ...
            'LineWidth', style.line_width, ...
            'MarkerSize', style.marker_size + 2, ...
            'MarkerFaceColor', style.colors(1, :));
    else
        plot(ax, frontier_table.i_deg, frontier_table.minimum_feasible_Ns, '-o', ...
            'Color', style.colors(1, :), ...
            'LineWidth', style.line_width, ...
            'MarkerSize', style.marker_size + 1, ...
            'MarkerFaceColor', style.colors(1, :));
    end
    for idx = 1:height(frontier_table)
        text(ax, frontier_table.i_deg(idx), frontier_table.minimum_feasible_Ns(idx) + 0.8, ...
            sprintf('%d', round(frontier_table.minimum_feasible_Ns(idx))), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Color', style.threshold_color);
    end
end

xlabel(ax, 'i (deg)');
ylabel(ax, 'Minimum feasible N_s');
title(ax, 'Inclination Frontier of Minimum Feasible Constellation Size');
grid(ax, 'on');
apply_mb_plot_domain_guardrail(ax, local_getfield_or(frontier_table, 'i_deg', []), local_getfield_or(frontier_table, 'minimum_feasible_Ns', []), struct( ...
    'min_span', 10, ...
    'auto_ylim', true, ...
    'empty_message', 'No valid frontier points in current search domain', ...
    'domain_summary', 'Frontier plot uses only finite minimum-feasible points', ...
    'plot_domain_source', "frontier_guardrail"));
hold(ax, 'off');
end

function values = local_getfield_or(T, field_name, fallback)
if istable(T) && ismember(field_name, T.Properties.VariableNames)
    values = T.(field_name);
else
    values = fallback;
end
end
