function [sanity_table, sanity_flags] = stage11_sanity_checks(out, cfg)
%STAGE11_SANITY_CHECKS Run Stage11 certificate-independence sanity checks.

    if nargin < 2 || isempty(cfg)
        cfg = default_params();
    end
    cfg = stage11_prepare_cfg(cfg);

    tol = 1e-10;
    dominance_threshold = 0.95;

    eta_pi = local_get_column(out.window_table, 'eta_pi');
    delta_sub = local_get_column(out.window_table, 'truth_lambda_min') - local_get_column(out.window_table, 'L_sub');
    delta_new = local_get_column(out.window_table, 'truth_lambda_min') - local_get_column(out.window_table, 'L_new');
    best_source = strings(height(out.window_table), 1);
    if ismember('best_bound_source', out.window_table.Properties.VariableNames)
        best_source = string(out.window_table.best_bound_source);
    end

    reference_leak_ratio = mean(eta_pi < tol, 'omitnan');
    sub_overlap_ratio = mean(abs(delta_sub) < tol, 'omitnan');
    joint_gap_ratio = mean(abs(delta_new) < tol, 'omitnan');
    part_sub_ratio = mean(best_source == "sub", 'omitnan');

    sanity_flags = struct();
    sanity_flags.reference_leakage = reference_leak_ratio > 0.5;
    sanity_flags.sub_truth_overlap = sub_overlap_ratio > 0.5;
    sanity_flags.joint_gap_collapse = joint_gap_ratio > 0.5;
    sanity_flags.best_source_sub_dominance = ...
        (part_sub_ratio > dominance_threshold) && (sanity_flags.sub_truth_overlap || sanity_flags.joint_gap_collapse);

    sanity_table = table( ...
        min(eta_pi, [], 'omitnan'), median(eta_pi, 'omitnan'), max(eta_pi, [], 'omitnan'), reference_leak_ratio, ...
        min(delta_sub, [], 'omitnan'), median(delta_sub, 'omitnan'), max(delta_sub, [], 'omitnan'), sub_overlap_ratio, ...
        min(delta_new, [], 'omitnan'), median(delta_new, 'omitnan'), max(delta_new, [], 'omitnan'), joint_gap_ratio, ...
        part_sub_ratio, ...
        logical(sanity_flags.reference_leakage), ...
        logical(sanity_flags.sub_truth_overlap), ...
        logical(sanity_flags.joint_gap_collapse), ...
        logical(sanity_flags.best_source_sub_dominance), ...
        'VariableNames', { ...
            'eta_pi_min', 'eta_pi_median', 'eta_pi_max', 'reference_leak_ratio', ...
            'delta_sub_min', 'delta_sub_median', 'delta_sub_max', 'sub_overlap_ratio', ...
            'delta_new_min', 'delta_new_median', 'delta_new_max', 'joint_gap_ratio', ...
            'best_source_sub_ratio', ...
            'sanity_fail_reference_leakage', ...
            'sanity_fail_sub_truth_overlap', ...
            'sanity_fail_joint_gap_collapse', ...
            'sanity_fail_best_source_sub_dominance'});
end


function values = local_get_column(T, name)
    if ismember(name, T.Properties.VariableNames)
        values = T.(name);
    else
        values = nan(height(T), 1);
    end
end
