function [summary_table, confusion_table, label_count_table] = summarize_stage10E1_screening(scan_table_e1, cfg)
%SUMMARIZE_STAGE10E1_SCREENING
% Summarize refined Stage10.E.1 screening behavior.
%
% Two confusion views are reported:
%   1) accept_after_refine:
%        safe_pass + warn_pass are both considered eventual accepts
%   2) safe_only:
%        only safe_pass is considered direct accept
%
% The point is:
%   - safe_only measures strict no-refine accept behavior
%   - accept_after_refine measures the realistic pipeline where warn_pass
%     enters full-truth refinement rather than being directly rejected.

    cfg = stage10E1_prepare_cfg(cfg);

    truth = logical(scan_table_e1.truth_pass);
    pred_accept_after_refine = logical(scan_table_e1.pred_accept);
    pred_safe_only = logical(scan_table_e1.pred_accept_safe);

    [tp1, fp1, fn1, tn1] = local_conf(truth, pred_accept_after_refine);
    [tp2, fp2, fn2, tn2] = local_conf(truth, pred_safe_only);

    confusion_table = table( ...
        string({'accept_after_refine'; 'safe_only'}), ...
        [tp1; tp2], ...
        [fp1; fp2], ...
        [fn1; fn2], ...
        [tn1; tn2], ...
        'VariableNames', {'method','TP','FP','FN','TN'});

    labels = categorical(scan_table_e1.stage_label, {'reject','warn_pass','safe_pass'}, 'Ordinal', true);
    u = categories(labels);
    counts = zeros(numel(u),1);
    for k = 1:numel(u)
        counts(k) = sum(labels == u{k});
    end
    label_count_table = table(string(u), counts, 'VariableNames', {'stage_label','count'});

    N_total = height(scan_table_e1);
    N_truth_pass = sum(truth);
    N_truth_fail = sum(~truth);

    N_reject = sum(scan_table_e1.stage_label == "reject");
    N_warn = sum(scan_table_e1.stage_label == "warn_pass");
    N_safe = sum(scan_table_e1.stage_label == "safe_pass");

    % among truth-pass points, how many are sent to refine?
    N_truth_pass_warn = sum(truth & (scan_table_e1.stage_label == "warn_pass"));
    N_truth_pass_safe = sum(truth & (scan_table_e1.stage_label == "safe_pass"));

    % among truth-fail points, how many incorrectly become warn/safe?
    N_truth_fail_warn = sum((~truth) & (scan_table_e1.stage_label == "warn_pass"));
    N_truth_fail_safe = sum((~truth) & (scan_table_e1.stage_label == "safe_pass"));

    summary_table = table( ...
        N_total, ...
        N_truth_pass, ...
        N_truth_fail, ...
        N_reject, ...
        N_warn, ...
        N_safe, ...
        N_truth_pass_warn, ...
        N_truth_pass_safe, ...
        N_truth_fail_warn, ...
        N_truth_fail_safe, ...
        mean(abs(scan_table_e1.lambda_truth - scan_table_e1.lambda_zero)), ...
        mean(abs(scan_table_e1.lambda_truth - scan_table_e1.lambda_bcirc)), ...
        mean(scan_table_e1.eps_sb_2), ...
        'VariableNames', { ...
            'N_total', ...
            'N_truth_pass', ...
            'N_truth_fail', ...
            'N_reject', ...
            'N_warn', ...
            'N_safe', ...
            'N_truth_pass_warn', ...
            'N_truth_pass_safe', ...
            'N_truth_fail_warn', ...
            'N_truth_fail_safe', ...
            'mean_gap_truth_zero', ...
            'mean_gap_truth_bcirc', ...
            'mean_eps_sb_2'});
end


function [tp, fp, fn, tn] = local_conf(truth, pred)
    tp = sum(truth & pred);
    fp = sum(~truth & pred);
    fn = sum(truth & ~pred);
    tn = sum(~truth & ~pred);
end