function profile = stage14_joint_phase_orientation_scope_profile(scope_name)
%STAGE14_JOINT_PHASE_ORIENTATION_SCOPE_PROFILE
% Return representative Stage14.4 scope profile.

    if nargin < 1 || isempty(scope_name)
        scope_name = "A1";
    end

    scope_name = upper(string(scope_name));

    switch scope_name
        case "A1"
            profile = struct( ...
                'scope_name', "A1", ...
                'h_fixed_km', 1000, ...
                'i_deg', 40, ...
                'P', 8, ...
                'T', 6, ...
                'RAAN_values', 0:15:345);

        case "A2"
            % Chosen from the feasible region observed in Stage14 mainline A:
            % h=1000 km, i=60 deg, Ns=120 with feasible points already seen.
            profile = struct( ...
                'scope_name', "A2", ...
                'h_fixed_km', 1000, ...
                'i_deg', 60, ...
                'P', 10, ...
                'T', 12, ...
                'RAAN_values', 0:15:345);

        otherwise
            error('stage14_joint_phase_orientation_scope_profile:UnknownScope', ...
                'Unknown scope_name "%s". Supported: A1, A2.', char(scope_name));
    end
end
