function out = stage14_plot_joint_phase_ns_passratio_fusion(cfg, opts)
%STAGE14_PLOT_JOINT_PHASE_NS_PASSRATIO_FUSION
% Stage14.4 B-line enhancement:
%   For a fixed (h, i), scan a family of (P, T) designs.
%   For each design, aggregate pass_ratio over all (F, RAAN).
%   Then fuse by unique Ns = P*T and generate an enhanced pass-ratio plot.
%
% Output layers:
%   1) per-design table:
%        one row per (P, T), aggregated over all F and RAAN
%   2) fused-by-Ns table:
%        one row per unique Ns, fused across all designs sharing that Ns
%   3) figure:
%        max / mean / min fused pass-ratio versus Ns

    if nargin < 1 || isempty(cfg)
        cfg = default_params();
    end
    if nargin < 2 || isempty(opts)
        opts = struct();
    end

    local = struct();
    local.scope_name = "A1";
    local.h_km = [];
    local.i_deg = [];
    local.P_grid = [4 6 8 10 12];
    local.T_grid = [4 6 8 10 12];
    local.RAAN_values = 0:15:345;

    local.visible = "on";
    local.save_fig = true;
    local.save_table = true;
    local.quiet = false;
    local.timestamp = string(datestr(now, 'yyyymmdd_HHMMSS'));

    fn = fieldnames(opts);
    for k = 1:numel(fn)
        local.(fn{k}) = opts.(fn{k});
    end

    % scope_name 必须保持为标准 A1/A2，不能自造新名字
    profile = stage14_joint_phase_orientation_scope_profile(local.scope_name);
    if isempty(local.h_km)
        local.h_km = profile.h_fixed_km;
    end
    if isempty(local.i_deg)
        local.i_deg = profile.i_deg;
    end
    if isempty(local.RAAN_values)
        local.RAAN_values = profile.RAAN_values;
    end

    fig_dir = fullfile(cfg.paths.outputs, 'stage', 'stage14', 'figs');
    table_dir = fullfile(cfg.paths.outputs, 'stage', 'stage14');
    if ~exist(fig_dir, 'dir'), mkdir(fig_dir); end
    if ~exist(table_dir, 'dir'), mkdir(table_dir); end

    rows = {};
    row_idx = 0;

    for ip = 1:numel(local.P_grid)
        P = local.P_grid(ip);
        for it = 1:numel(local.T_grid)
            T = local.T_grid(it);
            F_values = 0:(P - 1);

            % 内部调用仍然使用标准 scope_name=A1/A2
            joint_out = stage14_joint_phase_orientation(cfg, struct( ...
                'scope_name', local.scope_name, ...
                'h_fixed_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'P', P, ...
                'T', T, ...
                'F_values', F_values, ...
                'RAAN_values', local.RAAN_values, ...
                'save_fig', false, ...
                'save_table', false, ...
                'visible', 'off', ...
                'plot_visible', 'off', ...
                'do_plot', false, ...
                'do_formal_package', false, ...
                'do_postprocess', false, ...
                'do_analysis', false, ...
                'quiet', true));

            S = joint_out.grid.summary_table;
            assert(~isempty(S), 'Empty summary_table for P=%d, T=%d.', P, T);

            row_idx = row_idx + 1;
            rows(row_idx, :) = { ...
                string(local.scope_name), ...
                local.h_km, ...
                local.i_deg, ...
                P, ...
                T, ...
                P*T, ...
                numel(F_values), ...
                numel(local.RAAN_values), ...
                min(S.pass_ratio), ...
                mean(S.pass_ratio), ...
                max(S.pass_ratio), ...
                min(S.D_G_mean), ...
                mean(S.D_G_mean), ...
                max(S.D_G_mean), ...
                min(S.D_G_min), ...
                mean(S.D_G_min), ...
                max(S.D_G_min) ...
                }; %#ok<AGROW>

            if ~local.quiet
                fprintf('[stage14-ns-fusion] scope=%s | i=%g | P=%d | T=%d | Ns=%d | pass[min/mean/max]=[%.6f, %.6f, %.6f]\n', ...
                    char(local.scope_name), local.i_deg, P, T, P*T, ...
                    min(S.pass_ratio), mean(S.pass_ratio), max(S.pass_ratio));
            end
        end
    end

    per_design_table = cell2table(rows, 'VariableNames', { ...
        'scope_name', ...
        'h_km', ...
        'i_deg', ...
        'P', ...
        'T', ...
        'Ns', ...
        'n_F', ...
        'n_RAAN', ...
        'pass_ratio_min_over_FRAAN', ...
        'pass_ratio_mean_over_FRAAN', ...
        'pass_ratio_max_over_FRAAN', ...
        'DG_mean_min_over_FRAAN', ...
        'DG_mean_mean_over_FRAAN', ...
        'DG_mean_max_over_FRAAN', ...
        'DG_min_min_over_FRAAN', ...
        'DG_min_mean_over_FRAAN', ...
        'DG_min_max_over_FRAAN' ...
        });

    Ns_unique = unique(per_design_table.Ns(:))';
    fused_rows = zeros(numel(Ns_unique), 5);
    for k = 1:numel(Ns_unique)
        Ns = Ns_unique(k);
        sub = per_design_table(per_design_table.Ns == Ns, :);

        fused_rows(k, :) = [ ...
            Ns, ...
            min(sub.pass_ratio_min_over_FRAAN), ...
            mean(sub.pass_ratio_mean_over_FRAAN), ...
            max(sub.pass_ratio_max_over_FRAAN), ...
            height(sub) ...
            ];
    end

    fused_by_Ns_table = array2table(fused_rows, 'VariableNames', { ...
        'Ns', ...
        'pass_ratio_min_fused', ...
        'pass_ratio_mean_fused', ...
        'pass_ratio_max_fused', ...
        'n_designs' ...
        });

    fig = figure('Visible', char(local.visible));
    hold on;
    plot(fused_by_Ns_table.Ns, fused_by_Ns_table.pass_ratio_mean_fused, '-o', 'LineWidth', 1.5, 'MarkerSize', 7);
    plot(fused_by_Ns_table.Ns, fused_by_Ns_table.pass_ratio_min_fused, '--s', 'LineWidth', 1.2, 'MarkerSize', 6);
    plot(fused_by_Ns_table.Ns, fused_by_Ns_table.pass_ratio_max_fused, ':d', 'LineWidth', 1.2, 'MarkerSize', 7);
    grid on;
    box on;
    xlabel('$N_s$', 'Interpreter', 'latex');
    ylabel('$\mathrm{pass\ ratio}$', 'Interpreter', 'latex');
    ylim([0 1.05]);
    title({ ...
        sprintf('Stage14.4 %s: fused pass-ratio profile versus $N_s$', char(local.scope_name)), ...
        sprintf('$h=%g\\ \\mathrm{km},\\ i=%g^\\circ$, aggregated over all $(F,\\Omega)$ and fused over $(P,T)$ with same $N_s$', ...
            local.h_km, local.i_deg) ...
        }, 'Interpreter', 'latex');
    legend({'mean','min','max'}, 'Interpreter', 'latex', 'Location', 'best');

    out = struct();
    out.scope_name = string(local.scope_name);
    out.h_km = local.h_km;
    out.i_deg = local.i_deg;
    out.per_design_table = per_design_table;
    out.fused_by_Ns_table = fused_by_Ns_table;
    out.files = struct();
    out.files.fig_dir = fig_dir;
    out.files.table_dir = table_dir;
    out.files.passratio_fusion_png = "";
    out.files.per_design_csv = "";
    out.files.fused_by_Ns_csv = "";

    scope = char(string(local.scope_name));
    tag = char(local.timestamp);

    if local.save_fig
        out.files.passratio_fusion_png = fullfile(fig_dir, ...
            sprintf('stage14_%s_joint_phase_passratio_fused_by_Ns_%s.png', scope, tag));
        exportgraphics(fig, out.files.passratio_fusion_png, 'Resolution', 220);
    end

    if local.save_table
        out.files.per_design_csv = fullfile(table_dir, ...
            sprintf('stage14_%s_joint_phase_passratio_per_design_%s.csv', scope, tag));
        out.files.fused_by_Ns_csv = fullfile(table_dir, ...
            sprintf('stage14_%s_joint_phase_passratio_fused_by_Ns_%s.csv', scope, tag));
        writetable(per_design_table, out.files.per_design_csv);
        writetable(fused_by_Ns_table, out.files.fused_by_Ns_csv);
    end

    if ~local.quiet
        fprintf('\n=== Stage14.4 Ns pass-ratio fusion (%s) ===\n', scope);
        fprintf('h_km              : %g\n', local.h_km);
        fprintf('i_deg             : %g\n', local.i_deg);
        fprintf('P_grid            : '); disp(local.P_grid);
        fprintf('T_grid            : '); disp(local.T_grid);
        fprintf('RAAN count        : %d\n', numel(local.RAAN_values));
        fprintf('per-design rows   : %d\n', height(per_design_table));
        fprintf('unique Ns rows    : %d\n', height(fused_by_Ns_table));
        fprintf('fusion fig        : %s\n', out.files.passratio_fusion_png);
        fprintf('per-design csv    : %s\n', out.files.per_design_csv);
        fprintf('fused-by-Ns csv   : %s\n\n', out.files.fused_by_Ns_csv);
        disp(fused_by_Ns_table);
    end
end
