function out = run_stage14_openD(cfg, interactive, opts)
%RUN_STAGE14_OPEND
% Unified runner for Stage14 mainline A.
%
% New additions:
%   - preset = 'smoke' | 'production_stage05_aligned'
%   - ns_stats now defaults to Stage05-aligned production Ns_list
%   - mainline_A_full defaults to Stage05-aligned production search range

    proj_root = fileparts(fileparts(mfilename('fullpath')));
    if ~isempty(proj_root), addpath(proj_root); end
    startup();

    if nargin < 1 || isempty(cfg)
        cfg = default_params();
    end
    if nargin < 2 || isempty(interactive)
        interactive = false;
    end
    if nargin < 3 || isempty(opts)
        opts = struct();
    end

    local = struct();
    local.mode = 'mainline_A_full';
    local.preset = 'production_stage05_aligned';

    local.h_km = 1000;
    local.F = cfg.stage05.F_fixed;
    local.i_deg = 40;
    local.i_list = [30 40 50 60 70 80 90];
    local.P = 8;
    local.T = 6;
    local.Ns = 48;
    local.Ns_list = [];

    local.RAAN_scan_deg = 0:30:330;
    local.P_grid = [4 6 8 10 12];
    local.T_grid = [4 6 8 10 12];

    local.visible = "on";
    local.save_fig = true;
    local.save_table = true;
    local.make_plot = false;
    local.quiet = false;

    local.case_limit = inf;
    local.use_early_stop = false;
    local.hard_case_first = true;
    local.require_pass_ratio = 1.0;
    local.require_D_G_min = 1.0;
    local.progress_every = 25;
    local.save_cache = true;

    fn = fieldnames(opts);
    for k = 1:numel(fn)
        local.(fn{k}) = opts.(fn{k});
    end

    local = local_apply_preset(local);

    mode = lower(string(local.mode));
    out = struct();
    out.mode = char(mode);
    out.preset = local.preset;

    if interactive
        fprintf('[run_stages] Stage14 mainline A modes:\n');
        fprintf('  raw_grid\n');
        fprintf('  raan_profile\n');
        fprintf('  ns_envelope\n');
        fprintf('  ns_stats\n');
        fprintf('  multii_compare\n');
        fprintf('  mainline_A_full\n\n');
        fprintf('[run_stages] Current preset: %s\n\n', local.preset);
    end

    switch mode
        case "raw_grid"
            fprintf('[run_stages] === Stage14.1 mainline: openD raw RAAN scan ===\n');
            out.raw_grid = stage14_scan_openD_raan_grid(cfg, local_make_raw_grid_opts(local));
            fprintf('[run_stages] Stage14.1 completed.\n');

        case "raan_profile"
            fprintf('[run_stages] === Stage14.2 mainline: fixed-design RAAN profile ===\n');
            out.raan_profile = stage14_plot_raan_profiles(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'P', local.P, ...
                'T', local.T, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table));
            fprintf('[run_stages] Stage14.2 fixed-design profile completed.\n');

        case "ns_envelope"
            fprintf('[run_stages] === Stage14.2 mainline: Ns-envelope profile ===\n');
            out.ns_envelope = stage14_plot_ns_envelopes(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'Ns', local.Ns, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.2 Ns-envelope profile completed.\n');

        case "ns_stats"
            fprintf('[run_stages] === Stage14.3 mainline: multi-Ns stats ===\n');
            out.ns_stats = stage14_plot_multi_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.3 multi-Ns stats completed.\n');

        case "multii_compare"
            fprintf('[run_stages] === Stage14.3 mainline: multi-i comparison ===\n');
            out.multii_compare = stage14_plot_multi_i_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_list', local.i_list, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.3 multi-i comparison completed.\n');

        case "mainline_a_full"
            fprintf('[run_stages] === Stage14 mainline A full chain ===\n');
            fprintf('[run_stages] preset = %s\n', local.preset);

            out.raw_grid = stage14_scan_openD_raan_grid(cfg, local_make_raw_grid_opts(local));

            out.raan_profile = stage14_plot_raan_profiles(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'P', local.P, ...
                'T', local.T, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table));

            out.ns_envelope = stage14_plot_ns_envelopes(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'Ns', local.Ns, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));

            out.ns_stats = stage14_plot_multi_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));

            out.multii_compare = stage14_plot_multi_i_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_list', local.i_list, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'quiet', local.quiet));

            fprintf('[run_stages] Stage14 mainline A full chain completed.\n');

        otherwise
            error('run_stage14_openD:UnknownMode', ...
                'Unknown mode "%s". Supported modes: raw_grid, raan_profile, ns_envelope, ns_stats, multii_compare, mainline_A_full.', ...
                char(mode));
    end
end

function local = local_apply_preset(local)
    preset = lower(string(local.preset));

    switch preset
        case "smoke"
            if isempty(local.i_list)
                local.i_list = local.i_deg;
            end
            if isempty(local.Ns_list)
                local.Ns_list = unique(local.P_grid(:) .* local.T_grid(:))';
            end

        case "production_stage05_aligned"
            local.P_grid = [4 6 8 10 12];
            local.T_grid = [4 6 8 10 12];
            local.RAAN_scan_deg = 0:30:330;
            local.case_limit = inf;
            local.use_early_stop = false;
            local.hard_case_first = true;
            local.require_pass_ratio = 1.0;
            local.require_D_G_min = 1.0;

            if isempty(local.i_list)
                local.i_list = [30 40 50 60 70 80 90];
            end
            if isempty(local.Ns_list)
                local.Ns_list = unique(local.P_grid(:) .* local.T_grid(:))';
            end

        otherwise
            error('run_stage14_openD:UnknownPreset', ...
                'Unknown preset "%s". Supported presets: smoke, production_stage05_aligned.', ...
                char(preset));
    end
end

function raw_opts = local_make_raw_grid_opts(local)
    raw_opts = struct( ...
        'h_km', local.h_km, ...
        'F', local.F, ...
        'i_grid_deg', local.i_list, ...
        'P_grid', local.P_grid, ...
        'T_grid', local.T_grid, ...
        'RAAN_scan_deg', local.RAAN_scan_deg, ...
        'case_limit', local.case_limit, ...
        'use_early_stop', local.use_early_stop, ...
        'hard_case_first', local.hard_case_first, ...
        'require_pass_ratio', local.require_pass_ratio, ...
        'require_D_G_min', local.require_D_G_min, ...
        'progress_every', local.progress_every, ...
        'save_cache', local.save_cache, ...
        'save_table', local.save_table, ...
        'make_plot', local.make_plot);
end
