function out = run_stage14_openD(cfg, interactive, opts)
%RUN_STAGE14_OPEND
% Unified runner for Stage14 mainline A and Stage14.4 entry.

    proj_root = fileparts(fileparts(mfilename('fullpath')));
    if ~isempty(proj_root), addpath(proj_root); end
    cfg_missing = (nargin < 1 || isempty(cfg));

    if nargin < 2 || isempty(interactive)
        interactive = false;
    end
    if nargin < 3 || isempty(opts)
        opts = struct();
    end

    default_F = 1;
    if ~cfg_missing && isfield(cfg, 'stage05') && isstruct(cfg.stage05) && isfield(cfg.stage05, 'F_fixed')
        default_F = cfg.stage05.F_fixed;
    end

    local = struct();
    local.mode = 'mainline_A_full';
    local.preset = 'production_stage05_aligned';

    local.h_km = 1000;
    local.F = default_F;
    local.i_deg = 40;
    local.i_list = [30 40 50 60 70 80 90];

    local.P = 8;
    local.T = 6;
    local.Ns = 48;
    local.Ns_list = [];

    local.scope_name = "A1";

    local.RAAN_scan_deg = 0:30:330;
    local.RAAN_joint_deg = 0:15:345;
    local.F_values = [];

    local.P_grid = [4 6 8 10 12];
    local.T_grid = [4 6 8 10 12];

    local.visible = "on";
    local.save_fig = true;
    local.save_table = true;
    local.make_plot = false;
    local.quiet = false;
    local.do_startup = cfg_missing;
    local.startup_force = false;
    local.startup_quiet = true;

    local.case_limit = inf;
    local.use_early_stop = false;
    local.hard_case_first = true;
    local.require_pass_ratio = 1.0;
    local.require_D_G_min = 1.0;
    local.progress_every = 25;
    local.save_cache = true;

    local.do_postprocess = true;
    local.do_analysis = true;
    local.do_formal_package = true;

    early_fields = {'preset', 'do_startup', 'startup_force', 'startup_quiet'};
    for k = 1:numel(early_fields)
        key = early_fields{k};
        if isfield(opts, key)
            local.(key) = opts.(key);
        end
    end

    if local.do_startup
        local_run_startup(local.startup_force, local.startup_quiet);
    end

    if cfg_missing
        cfg = default_params();
    end
    if ~isfield(opts, 'F') && isfield(cfg, 'stage05') && isfield(cfg.stage05, 'F_fixed')
        local.F = cfg.stage05.F_fixed;
    end

    local = local_apply_preset(local);

    fn = fieldnames(opts);
    for k = 1:numel(fn)
        local.(fn{k}) = opts.(fn{k});
    end

    if isempty(local.F_values)
        local.F_values = 0:(local.P - 1);
    end

    mode = lower(string(local.mode));
    out = struct();
    out.mode = char(mode);
    out.preset = char(local.preset);
    out.Ns_list = local.Ns_list;

    if interactive
        fprintf('[run_stages] Stage14 modes:\n');
        fprintf('  raw_grid\n');
        fprintf('  raan_profile\n');
        fprintf('  ns_envelope\n');
        fprintf('  ns_stats\n');
        fprintf('  multii_compare\n');
        fprintf('  joint_phase_orientation_a1\n');
        fprintf('  joint_phase_orientation_a2\n');
        fprintf('  joint_phase_ns_passratio_a1\n');
        fprintf('  joint_phase_ns_passratio_a2\n');
        fprintf('  mainline_A_full\n\n');
        fprintf('[run_stages] Current preset: %s\n', local.preset);
        fprintf('[run_stages] Current Ns_list: ');
        disp(local.Ns_list);
        fprintf('\n');
    end

    if any(mode == ["raw_grid", "mainline_a_full"])
        raw_cfg = stage14_default_config(cfg, local_make_raw_grid_opts(local));
        local_prepare_parallel_pool(raw_cfg);
    end

    switch mode
        case "raw_grid"
            fprintf('[run_stages] === Stage14.1 mainline: openD raw RAAN scan ===\n');
            out.raw_grid = stage14_scan_openD_raan_grid(cfg, local_make_raw_grid_opts(local));
            fprintf('[run_stages] Stage14.1 completed.\n');

        case "raan_profile"
            fprintf('[run_stages] === Stage14.2 mainline: fixed-design RAAN profile ===\n');
            out.raan_profile = stage14_plot_raan_profiles(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'P', local.P, ...
                'T', local.T, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table));
            fprintf('[run_stages] Stage14.2 fixed-design profile completed.\n');

        case "ns_envelope"
            fprintf('[run_stages] === Stage14.2 mainline: Ns-envelope profile ===\n');
            out.ns_envelope = stage14_plot_ns_envelopes(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'Ns', local.Ns, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.2 Ns-envelope profile completed.\n');

        case "ns_stats"
            fprintf('[run_stages] === Stage14.3 mainline: multi-Ns stats ===\n');
            fprintf('[run_stages] preset = %s\n', local.preset);
            fprintf('[run_stages] Ns_list = ');
            disp(local.Ns_list);

            out.ns_stats = stage14_plot_multi_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.3 multi-Ns stats completed.\n');

        case "multii_compare"
            fprintf('[run_stages] === Stage14.3 mainline: multi-i comparison ===\n');
            fprintf('[run_stages] preset = %s\n', local.preset);
            fprintf('[run_stages] Ns_list = ');
            disp(local.Ns_list);

            out.multii_compare = stage14_plot_multi_i_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_list', local.i_list, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.3 multi-i comparison completed.\n');

        case "joint_phase_orientation_a1"
            fprintf('[run_stages] === Stage14.4 B-line: joint phase-orientation sensitivity (A1) ===\n');
            out.joint_phase_orientation = stage14_joint_phase_orientation(cfg, struct( ...
                'scope_name', "A1", ...
                'h_fixed_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'P', local.P, ...
                'T', local.T, ...
                'F_values', local.F_values, ...
                'RAAN_values', local.RAAN_joint_deg, ...
                'case_limit', local.case_limit, ...
                'use_early_stop', local.use_early_stop, ...
                'hard_case_first', local.hard_case_first, ...
                'require_pass_ratio', local.require_pass_ratio, ...
                'require_D_G_min', local.require_D_G_min, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'visible', local.visible, ...
                'quiet', local.quiet, ...
                'do_postprocess', local.do_postprocess, ...
                'do_analysis', local.do_analysis, ...
                'do_formal_package', local.do_formal_package));
            fprintf('[run_stages] Stage14.4 B-line A1 completed.\n');

        case "joint_phase_orientation_a2"
            fprintf('[run_stages] === Stage14.4 B-line: joint phase-orientation sensitivity (A2) ===\n');
            out.joint_phase_orientation = stage14_joint_phase_orientation(cfg, struct( ...
                'scope_name', "A2", ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'visible', local.visible, ...
                'quiet', local.quiet, ...
                'do_postprocess', local.do_postprocess, ...
                'do_analysis', local.do_analysis, ...
                'do_formal_package', local.do_formal_package));
            fprintf('[run_stages] Stage14.4 B-line A2 completed.\n');

        case "joint_phase_ns_passratio_a1"
            fprintf('[run_stages] === Stage14.4 B-line: joint-phase Ns pass-ratio fusion (A1) ===\n');
            out.joint_phase_ns_passratio = stage14_plot_joint_phase_ns_passratio_fusion(cfg, struct( ...
                'scope_name', "A1", ...
                'P_grid', local.P_grid, ...
                'T_grid', local.T_grid, ...
                'RAAN_values', local.RAAN_joint_deg, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.4 B-line Ns-fusion A1 completed.\n');

        case "joint_phase_ns_passratio_a2"
            fprintf('[run_stages] === Stage14.4 B-line: joint-phase Ns pass-ratio fusion (A2) ===\n');
            out.joint_phase_ns_passratio = stage14_plot_joint_phase_ns_passratio_fusion(cfg, struct( ...
                'scope_name', "A2", ...
                'P_grid', local.P_grid, ...
                'T_grid', local.T_grid, ...
                'RAAN_values', local.RAAN_joint_deg, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.4 B-line Ns-fusion A2 completed.\n');

        case "mainline_a_full"
            fprintf('[run_stages] === Stage14 mainline A full chain ===\n');
            fprintf('[run_stages] preset = %s\n', local.preset);
            fprintf('[run_stages] Ns_list = ');
            disp(local.Ns_list);

            out.raw_grid = stage14_scan_openD_raan_grid(cfg, local_make_raw_grid_opts(local));

            out.raan_profile = stage14_plot_raan_profiles(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'P', local.P, ...
                'T', local.T, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table));

            out.ns_envelope = stage14_plot_ns_envelopes(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'Ns', local.Ns, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));

            out.ns_stats = stage14_plot_multi_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));

            out.multii_compare = stage14_plot_multi_i_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_list', local.i_list, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'quiet', local.quiet));

            fprintf('[run_stages] Stage14 mainline A full chain completed.\n');

        otherwise
            error('run_stage14_openD:UnknownMode', ...
                ['Unknown mode "%s". Supported modes: raw_grid, raan_profile, ns_envelope, ', ...
                 'ns_stats, multii_compare, joint_phase_orientation_a1, joint_phase_orientation_a2, ', ...
                 'joint_phase_ns_passratio_a1, joint_phase_ns_passratio_a2, mainline_A_full.'], ...
                char(mode));
    end
end

function local = local_apply_preset(local)
    preset = lower(string(local.preset));

    switch preset
        case "smoke"
            if isempty(local.i_list)
                local.i_list = local.i_deg;
            end
            if isempty(local.Ns_list)
                local.Ns_list = local_unique_ns_from_grids(local.P_grid, local.T_grid);
            end

        case "production_stage05_aligned"
            local.P_grid = [4 6 8 10 12];
            local.T_grid = [4 6 8 10 12];
            local.RAAN_scan_deg = 0:30:330;
            local.case_limit = inf;
            local.use_early_stop = false;
            local.hard_case_first = true;
            local.require_pass_ratio = 1.0;
            local.require_D_G_min = 1.0;

            if isempty(local.i_list)
                local.i_list = [30 40 50 60 70 80 90];
            end
            if isempty(local.Ns_list)
                local.Ns_list = local_unique_ns_from_grids(local.P_grid, local.T_grid);
            end

        otherwise
            error('run_stage14_openD:UnknownPreset', ...
                'Unknown preset "%s". Supported presets: smoke, production_stage05_aligned.', ...
                char(preset));
    end
end

function raw_opts = local_make_raw_grid_opts(local)
    raw_opts = struct( ...
        'h_km', local.h_km, ...
        'F', local.F, ...
        'i_grid_deg', local.i_list, ...
        'P_grid', local.P_grid, ...
        'T_grid', local.T_grid, ...
        'RAAN_scan_deg', local.RAAN_scan_deg, ...
        'case_limit', local.case_limit, ...
        'use_early_stop', local.use_early_stop, ...
        'hard_case_first', local.hard_case_first, ...
        'require_pass_ratio', local.require_pass_ratio, ...
        'require_D_G_min', local.require_D_G_min, ...
        'progress_every', local.progress_every, ...
        'save_cache', local.save_cache, ...
        'save_table', local.save_table, ...
        'make_plot', local.make_plot);
end

function Ns_list = local_unique_ns_from_grids(P_grid, T_grid)
    [Pm, Tm] = ndgrid(P_grid(:), T_grid(:));
    Ns_list = unique(Pm(:) .* Tm(:))';
end

function local_run_startup(force_startup, quiet_startup)
    if quiet_startup
        if force_startup
            evalc('startup(''force'', true);');
        else
            evalc('startup(''force'', false);');
        end
    else
        startup('force', logical(force_startup));
    end
end

function local_prepare_parallel_pool(cfg)
    if ~isfield(cfg, 'stage14') || ~isstruct(cfg.stage14) || ...
            ~isfield(cfg.stage14, 'parallel') || ~isstruct(cfg.stage14.parallel) || ...
            ~logical(cfg.stage14.parallel.enable)
        return;
    end

    profile_name = 'local';
    if isfield(cfg.stage14.parallel, 'prefer_threads') && cfg.stage14.parallel.prefer_threads
        profile_name = 'threads';
    end

    num_workers = [];
    if isfield(cfg.stage14.parallel, 'max_workers') && ~isempty(cfg.stage14.parallel.max_workers)
        num_workers = cfg.stage14.parallel.max_workers;
    end

    try
        ensure_parallel_pool(profile_name, num_workers);
    catch
    end
end
