function out = run_stage14_openD(cfg, interactive, opts)
%RUN_STAGE14_OPEND
% Unified entry for Stage14 mainline A (openD / fixed F_ref):
%
% Supported modes:
%   - raw_grid
%   - raan_profile
%   - ns_envelope
%   - ns_stats
%   - multii_compare
%   - mainline_A_full
%
% Notes:
%   Stage14 mainline A corresponds to:
%     Stage14.1 : raw RAAN-expanded grid
%     Stage14.2 : fixed-design RAAN profile + Ns-envelope profile
%     Stage14.3 : Ns-level aggregate stats + multi-i comparison
%
%   This runner only handles mainline A. Legacy joint (F,RAAN) exploration
%   remains archived and is NOT invoked here.

    proj_root = fileparts(fileparts(mfilename('fullpath')));
    if ~isempty(proj_root), addpath(proj_root); end
    startup();

    if nargin < 1 || isempty(cfg)
        cfg = default_params();
    end
    if nargin < 2 || isempty(interactive)
        interactive = (nargin == 0);
    end
    if nargin < 3 || isempty(opts)
        opts = struct();
    end

    local = struct();
    local.mode = 'mainline_A_full';

    % shared mainline A defaults
    local.h_km = 1000;
    local.F = cfg.stage05.F_fixed;
    local.i_deg = 40;
    local.i_list = [30 40 50 60 70 80 90];
    local.P = 8;
    local.T = 6;
    local.Ns = 48;
    local.Ns_list = [];
    local.RAAN_scan_deg = 0:30:330;

    local.visible = "on";
    local.save_fig = true;
    local.save_table = true;
    local.make_plot = false;
    local.quiet = false;

    % Stage14.1 search-grid defaults
    local.P_grid = [4 6 8 10 12];
    local.T_grid = [4 6 8 10 12];
    local.case_limit = inf;
    local.use_early_stop = false;
    local.hard_case_first = true;
    local.require_pass_ratio = 1.0;
    local.require_D_G_min = 1.0;
    local.progress_every = 25;
    local.save_cache = true;

    fn = fieldnames(opts);
    for k = 1:numel(fn)
        local.(fn{k}) = opts.(fn{k});
    end

    if interactive
        fprintf('[run_stages] Stage14 mainline A modes:\n');
        fprintf('  raw_grid       : Stage14.1 raw (i,P,T,RAAN) grid\n');
        fprintf('  raan_profile   : Stage14.2 fixed-design RAAN profile\n');
        fprintf('  ns_envelope    : Stage14.2 fixed-(i,Ns) PT-envelope over RAAN\n');
        fprintf('  ns_stats       : Stage14.3 single-i multi-Ns stats\n');
        fprintf('  multii_compare : Stage14.3 multi-i multi-Ns comparison\n');
        fprintf('  mainline_A_full: run the mainline A chain\n\n');
    end

    mode = lower(string(local.mode));
    out = struct();
    out.mode = char(mode);

    switch mode
        case "raw_grid"
            fprintf('[run_stages] === Stage14.1 mainline: openD raw RAAN scan ===\n');
            out.raw_grid = stage14_scan_openD_raan_grid(cfg, local_make_raw_grid_opts(local));
            fprintf('[run_stages] Stage14.1 completed.\n');

        case "raan_profile"
            fprintf('[run_stages] === Stage14.2 mainline: fixed-design RAAN profile ===\n');
            out.raan_profile = stage14_plot_raan_profiles(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'P', local.P, ...
                'T', local.T, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table));
            fprintf('[run_stages] Stage14.2 fixed-design profile completed.\n');

        case "ns_envelope"
            fprintf('[run_stages] === Stage14.2 mainline: Ns-envelope profile ===\n');
            out.ns_envelope = stage14_plot_ns_envelopes(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'Ns', local.Ns, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.2 Ns-envelope profile completed.\n');

        case "ns_stats"
            fprintf('[run_stages] === Stage14.3 mainline: multi-Ns stats ===\n');
            out.ns_stats = stage14_plot_multi_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.3 multi-Ns stats completed.\n');

        case "multii_compare"
            fprintf('[run_stages] === Stage14.3 mainline: multi-i comparison ===\n');
            out.multii_compare = stage14_plot_multi_i_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_list', local.i_list, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'quiet', local.quiet));
            fprintf('[run_stages] Stage14.3 multi-i comparison completed.\n');

        case "mainline_a_full"
            fprintf('[run_stages] === Stage14 mainline A full chain ===\n');

            % Stage14.1
            out.raw_grid = stage14_scan_openD_raan_grid(cfg, local_make_raw_grid_opts(local));

            % Stage14.2 fixed-design profile
            out.raan_profile = stage14_plot_raan_profiles(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'P', local.P, ...
                'T', local.T, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table));

            % Stage14.2 Ns-envelope
            out.ns_envelope = stage14_plot_ns_envelopes(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'Ns', local.Ns, ...
                'F', local.F, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));

            % Stage14.3 single-i stats
            out.ns_stats = stage14_plot_multi_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_deg', local.i_deg, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'save_table', local.save_table, ...
                'quiet', local.quiet));

            % Stage14.3 multi-i comparison
            out.multii_compare = stage14_plot_multi_i_ns_stats(cfg, struct( ...
                'h_km', local.h_km, ...
                'i_list', local.i_list, ...
                'F', local.F, ...
                'Ns_list', local.Ns_list, ...
                'visible', local.visible, ...
                'save_fig', local.save_fig, ...
                'quiet', local.quiet));

            fprintf('[run_stages] Stage14 mainline A full chain completed.\n');

        otherwise
            error('run_stage14_openD:UnknownMode', ...
                'Unknown mode "%s". Supported modes: raw_grid, raan_profile, ns_envelope, ns_stats, multii_compare, mainline_A_full.', ...
                char(mode));
    end
end

function raw_opts = local_make_raw_grid_opts(local)
    raw_opts = struct( ...
        'h_km', local.h_km, ...
        'F', local.F, ...
        'i_grid_deg', local.i_list, ...
        'P_grid', local.P_grid, ...
        'T_grid', local.T_grid, ...
        'RAAN_scan_deg', local.RAAN_scan_deg, ...
        'case_limit', local.case_limit, ...
        'use_early_stop', local.use_early_stop, ...
        'hard_case_first', local.hard_case_first, ...
        'require_pass_ratio', local.require_pass_ratio, ...
        'require_D_G_min', local.require_D_G_min, ...
        'progress_every', local.progress_every, ...
        'save_cache', local.save_cache, ...
        'save_table', local.save_table, ...
        'make_plot', local.make_plot);

    % If caller explicitly wants a single inclination in raw_grid mode,
    % local.i_list can be set to scalar via opts.i_list, or local.i_deg can
    % be mirrored manually.
    if isscalar(local.i_list) && ~isnan(local.i_list)
        raw_opts.i_grid_deg = local.i_list;
    end
end
