function out = run_ch5r_phase10_compare_with_r9()
%RUN_CH5R_PHASE10_COMPARE_WITH_R9
% Compare current R9 main point against R10 Li-style interval backend.

out9 = run_ch5r_phase9_r9_closedloop(struct( ...
    'alpha_tau', 0.5, ...
    'save_outputs', false, ...
    'log_enable', false));

out10 = run_ch5r_phase10_li_backend_closedloop(struct( ...
    'save_outputs', false, ...
    'log_enable', false));

T = table( ...
    ["R9-real_koopman_pipe_feedback"; "R10-li_interval_backend"], ...
    [out9.result.bubble_metrics.total_valid_steps; out10.result.bubble_metrics.total_valid_steps], ...
    [out9.result.bubble_metrics.bubble_steps; out10.result.bubble_metrics.bubble_steps], ...
    [out9.result.bubble_metrics.bubble_time_s; out10.result.bubble_metrics.bubble_time_s], ...
    [out9.result.bubble_metrics.longest_bubble_time_s; out10.result.bubble_metrics.longest_bubble_time_s], ...
    [out9.result.bubble_metrics.max_bubble_depth; out10.result.bubble_metrics.max_bubble_depth], ...
    [out9.result.bubble_metrics.mean_bubble_depth; out10.result.bubble_metrics.mean_bubble_depth], ...
    [out9.result.cost_metrics.switch_count; out10.result.cost_metrics.switch_count], ...
    [out9.result.r9_tracking.mean_rmse_pos_km; out10.result.r10_tracking.mean_rmse_pos_km], ...
    [out9.result.r9_tracking.final_rmse_pos_km; out10.result.r10_tracking.final_rmse_pos_km], ...
    'VariableNames', { ...
        'policy', ...
        'valid_steps', ...
        'bubble_steps', ...
        'bubble_time_s', ...
        'longest_bubble_time_s', ...
        'max_bubble_depth', ...
        'mean_bubble_depth', ...
        'switch_count', ...
        'mean_rmse_pos_km', ...
        'final_rmse_pos_km'});

disp('=== [ch5r:R10-compare] R9 vs R10 summary ===')
disp(T)

out = struct();
out.out9 = out9;
out.out10 = out10;
out.summary_table = T;
out.ok = true;
end
