function out = run_ch5r_phase8_6c_counterfactual_test()
%RUN_CH5R_PHASE8_6C_COUNTERFACTUAL_TEST
% R8.6c:
%   Counterfactual tests on critical worst-window neighborhood.

cfg = default_ch5r_params(true);
cfg = default_ch5r_r85_li_methods_params(cfg);

cfg.r85f2.parallel.enable = true;
cfg.r85f2.logging.enable = true;
cfg.r85f2.logging.every_k = 160;

cfg.r85f4a.danger_weighted_gain.eta_switch = 1e6;
cfg.r85f4a.danger_weighted_gain.lookahead_steps = 60;
cfg.r85f4a.danger_weighted_gain.alpha_cross = 1e5;
cfg.r85f4a.danger_weighted_gain.beta_margin = 1;
cfg.r85f4a.danger_weighted_gain.eps_margin = 1e-6;

li_case = build_r85_li_case_from_current_case(cfg);
ch5case = li_case.base_case;

run_pta = run_online_policy_from_pair_bank(cfg, ch5case, 'pta');
run_obs = run_online_policy_from_pair_bank(cfg, ch5case, 'observability_family');
run_dwg = run_online_policy_from_pair_bank(cfg, ch5case, 'danger_weighted_gain');

k1 = 781;
k2 = 801;

cf(1) = evaluate_counterfactual_local_splice( ...
    ch5case, ...
    run_pta.selection_trace, ...
    run_obs.selection_trace, ...
    k1, k2, ...
    'PTA_online', ...
    'observability_family_online', ...
    'PTA_with_obs_tail'); %#ok<AGROW>

cf(2) = evaluate_counterfactual_local_splice( ...
    ch5case, ...
    run_dwg.selection_trace, ...
    run_obs.selection_trace, ...
    k1, k2, ...
    'danger_weighted_gain_online', ...
    'observability_family_online', ...
    'DWG_with_obs_tail'); %#ok<AGROW>

cf(3) = evaluate_counterfactual_local_splice( ...
    ch5case, ...
    run_obs.selection_trace, ...
    run_pta.selection_trace, ...
    k1, k2, ...
    'observability_family_online', ...
    'PTA_online', ...
    'OBS_with_pta_tail'); %#ok<AGROW>

cf(4) = evaluate_counterfactual_local_splice( ...
    ch5case, ...
    run_obs.selection_trace, ...
    run_dwg.selection_trace, ...
    k1, k2, ...
    'observability_family_online', ...
    'danger_weighted_gain_online', ...
    'OBS_with_dwg_tail'); %#ok<AGROW>

case_name = string({cf.new_tag})';
base_name = string({cf.base_tag})';
patch_name = string({cf.patch_tag})';

bubble_steps_base = arrayfun(@(s) s.m_base.summary.bubble_steps, cf)';
bubble_steps_cf = arrayfun(@(s) s.m_cf.summary.bubble_steps, cf)';
delta_bubble_steps = arrayfun(@(s) s.delta.bubble_steps, cf)';

max_bubble_depth_base = arrayfun(@(s) s.m_base.summary.max_bubble_depth, cf)';
max_bubble_depth_cf = arrayfun(@(s) s.m_cf.summary.max_bubble_depth, cf)';
delta_max_bubble_depth = arrayfun(@(s) s.delta.max_bubble_depth, cf)';

longest_bubble_span_base = arrayfun(@(s) s.m_base.summary.longest_bubble_span, cf)';
longest_bubble_span_cf = arrayfun(@(s) s.m_cf.summary.longest_bubble_span, cf)';
delta_longest_bubble_span = arrayfun(@(s) s.delta.longest_bubble_span, cf)';

mean_lambda_base = arrayfun(@(s) s.m_base.summary.mean_lambda_min_window, cf)';
mean_lambda_cf = arrayfun(@(s) s.m_cf.summary.mean_lambda_min_window, cf)';
delta_mean_lambda = arrayfun(@(s) s.delta.mean_lambda_min_window, cf)';

min_lambda_base = arrayfun(@(s) s.m_base.summary.min_lambda_min_window, cf)';
min_lambda_cf = arrayfun(@(s) s.m_cf.summary.min_lambda_min_window, cf)';
delta_min_lambda = arrayfun(@(s) s.delta.min_lambda_min_window, cf)';

switch_count_base = arrayfun(@(s) s.m_base.summary.switch_count, cf)';
switch_count_cf = arrayfun(@(s) s.m_cf.summary.switch_count, cf)';
delta_switch_count = arrayfun(@(s) s.delta.switch_count, cf)';

summary_table = table( ...
    case_name, ...
    base_name, ...
    patch_name, ...
    repmat(k1, numel(cf), 1), ...
    repmat(k2, numel(cf), 1), ...
    bubble_steps_base, ...
    bubble_steps_cf, ...
    delta_bubble_steps, ...
    max_bubble_depth_base, ...
    max_bubble_depth_cf, ...
    delta_max_bubble_depth, ...
    longest_bubble_span_base, ...
    longest_bubble_span_cf, ...
    delta_longest_bubble_span, ...
    mean_lambda_base, ...
    mean_lambda_cf, ...
    delta_mean_lambda, ...
    min_lambda_base, ...
    min_lambda_cf, ...
    delta_min_lambda, ...
    switch_count_base, ...
    switch_count_cf, ...
    delta_switch_count, ...
    'VariableNames', { ...
        'counterfactual_case', ...
        'base_policy', ...
        'patch_policy', ...
        'k1', ...
        'k2', ...
        'bubble_steps_base', ...
        'bubble_steps_cf', ...
        'delta_bubble_steps', ...
        'max_bubble_depth_base', ...
        'max_bubble_depth_cf', ...
        'delta_max_bubble_depth', ...
        'longest_bubble_span_base', ...
        'longest_bubble_span_cf', ...
        'delta_longest_bubble_span', ...
        'mean_lambda_base', ...
        'mean_lambda_cf', ...
        'delta_mean_lambda', ...
        'min_lambda_base', ...
        'min_lambda_cf', ...
        'delta_min_lambda', ...
        'switch_count_base', ...
        'switch_count_cf', ...
        'delta_switch_count'});

out_dir = fullfile(pwd, 'outputs', 'ch5_rebuild', 'phaseR8_6c_counterfactual_test');
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

stamp = char(datetime('now','Format','yyyyMMdd_HHmmss'));
csv_file = fullfile(out_dir, ['phaseR8_6c_counterfactual_test_' stamp '.csv']);
mat_file = fullfile(out_dir, ['phaseR8_6c_counterfactual_test_' stamp '.mat']);
md_file  = fullfile(out_dir, ['phaseR8_6c_counterfactual_test_' stamp '.md']);

writetable(summary_table, csv_file);
save(mat_file, 'cfg', 'summary_table', 'cf', 'run_pta', 'run_obs', 'run_dwg');

md = local_build_md(summary_table, csv_file, mat_file);
fid = fopen(md_file, 'w');
assert(fid >= 0, 'Failed to open markdown file: %s', md_file);
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '%s', md);

disp(' ')
disp('=== [ch5r:R8.6c] counterfactual critical-window test summary ===')
disp(summary_table)
disp(['csv file             : ' csv_file])
disp(['mat file             : ' mat_file])
disp(['md file              : ' md_file])

out = struct();
out.summary_table = summary_table;
out.cf = cf;
out.paths = struct( ...
    'csv_file', csv_file, ...
    'mat_file', mat_file, ...
    'md_file', md_file, ...
    'output_dir', out_dir);
out.ok = true;
end

function md = local_build_md(summary_table, csv_file, mat_file)
lines = {};
lines{end+1} = '# Phase R8.6c counterfactual critical-window test';
lines{end+1} = '';
lines{end+1} = ['- csv file = `', csv_file, '`'];
lines{end+1} = ['- mat file = `', mat_file, '`'];
lines{end+1} = '';
for i = 1:height(summary_table)
    lines{end+1} = sprintf(['- %s: base=%s, patch=%s, range=[%g,%g], ' ...
        'bubble_steps %g->%g (delta=%+g), ' ...
        'max_bubble_depth %g->%g (delta=%+g), ' ...
        'longest_bubble_span %g->%g (delta=%+g), ' ...
        'min_lambda %g->%g (delta=%+g), ' ...
        'switch_count %g->%g (delta=%+g)'], ...
        summary_table.counterfactual_case(i), ...
        summary_table.base_policy(i), ...
        summary_table.patch_policy(i), ...
        summary_table.k1(i), ...
        summary_table.k2(i), ...
        summary_table.bubble_steps_base(i), ...
        summary_table.bubble_steps_cf(i), ...
        summary_table.delta_bubble_steps(i), ...
        summary_table.max_bubble_depth_base(i), ...
        summary_table.max_bubble_depth_cf(i), ...
        summary_table.delta_max_bubble_depth(i), ...
        summary_table.longest_bubble_span_base(i), ...
        summary_table.longest_bubble_span_cf(i), ...
        summary_table.delta_longest_bubble_span(i), ...
        summary_table.min_lambda_base(i), ...
        summary_table.min_lambda_cf(i), ...
        summary_table.delta_min_lambda(i), ...
        summary_table.switch_count_base(i), ...
        summary_table.switch_count_cf(i), ...
        summary_table.delta_switch_count(i));
end
md = strjoin(lines, newline);
end
