function out = run_ch5r_phase10_small_smoke()
%RUN_CH5R_PHASE10_SMALL_SMOKE
% Very small smoke scan for R10:
% interval_steps in {20,30,40}
% min_support_ratio in {0.5,0.8}

grid_interval = [20, 30, 40];
grid_support = [0.5, 0.8];

rows = {};
for i = 1:numel(grid_interval)
    for j = 1:numel(grid_support)
        interval_steps = grid_interval(i);
        min_support_ratio = grid_support(j);

        overrides = struct();
        overrides.interval_steps = interval_steps;
        overrides.min_support_ratio = min_support_ratio;
        overrides.save_outputs = false;
        overrides.log_enable = false;

        t_case = tic;
        status = "ok";
        msg = "";

        try
            out10 = run_ch5r_phase10_li_backend_closedloop(overrides);
            bm = out10.result.bubble_metrics;
            cm = out10.result.cost_metrics;
            tr = out10.result.r10_tracking;

            rows(end+1,:) = { ...
                interval_steps, ...
                min_support_ratio, ...
                bm.total_valid_steps, ...
                bm.bubble_steps, ...
                bm.bubble_time_s, ...
                bm.longest_bubble_time_s, ...
                bm.max_bubble_depth, ...
                bm.mean_bubble_depth, ...
                cm.switch_count, ...
                tr.mean_rmse_pos_km, ...
                tr.final_rmse_pos_km, ...
                status, ...
                msg, ...
                toc(t_case)}; %#ok<AGROW>
        catch ME
            status = "error";
            msg = string(ME.message);

            rows(end+1,:) = { ...
                interval_steps, ...
                min_support_ratio, ...
                NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, ...
                status, ...
                msg, ...
                toc(t_case)}; %#ok<AGROW>
        end
    end
end

T = cell2table(rows, 'VariableNames', { ...
    'interval_steps', ...
    'min_support_ratio', ...
    'valid_steps', ...
    'bubble_steps', ...
    'bubble_time_s', ...
    'longest_bubble_time_s', ...
    'max_bubble_depth', ...
    'mean_bubble_depth', ...
    'switch_count', ...
    'mean_rmse_pos_km', ...
    'final_rmse_pos_km', ...
    'status', ...
    'message', ...
    'elapsed_s'});

disp('=== [ch5r:R10-small-smoke] summary ===')
disp(T)

assert(all(T.valid_steps == 742 | isnan(T.valid_steps)));
assert(all(T.status == "ok"));

out = struct();
out.summary_table = T;
out.ok = true;
end
