function out = run_ch5r_phase5_paramscan_smoke()
%RUN_CH5R_PHASE5_PARAMSCAN_SMOKE
% Small-grid smoke scan for R5 parameters.
%
% Goal:
% - verify program correctness and result packaging
% - do NOT aim for full tuning coverage
%
% Grid:
%   horizon_steps   in [10, 30, 50]
%   lambda_sw       in [100, 500, 1000]
%   min_hold_steps  in [1, 5]

horizon_grid = [10, 30, 50];
lambda_sw_grid = [100, 500, 1000];
min_hold_grid = [1, 5];

rows = {};
case_idx = 0;

for ih = 1:numel(horizon_grid)
    for il = 1:numel(lambda_sw_grid)
        for im = 1:numel(min_hold_grid)
            case_idx = case_idx + 1;

            overrides = struct();
            overrides.horizon_steps = horizon_grid(ih);
            overrides.lambda_sw = lambda_sw_grid(il);
            overrides.min_hold_steps = min_hold_grid(im);
            overrides.parallel_enable = false;
            overrides.log_enable = false;
            overrides.save_outputs = false;
            overrides.window_length_s = 60;
            overrides.window_mode = 'centered_full_only';
            overrides.window_exclude_incomplete_edges = true;

            t_case = tic;
            status = "ok";
            message = "";

            try
                out_case = run_ch5r_phase5_bubble_predictive(overrides);

                bm = out_case.result.bubble_metrics;
                cm = out_case.result.cost_metrics;
                rq = out_case.result.requirement;

                rows(end+1, :) = { ...
                    case_idx, ...
                    overrides.horizon_steps, ...
                    overrides.lambda_sw, ...
                    overrides.min_hold_steps, ...
                    bm.total_valid_steps, ...
                    bm.bubble_steps, ...
                    bm.bubble_fraction, ...
                    bm.bubble_time_s, ...
                    bm.longest_bubble_time_s, ...
                    bm.max_bubble_depth, ...
                    cm.switch_count, ...
                    cm.resource_score, ...
                    rq.min_margin, ...
                    status, ...
                    message, ...
                    toc(t_case)}; %#ok<AGROW>

            catch ME
                status = "error";
                message = string(ME.message);

                rows(end+1, :) = { ...
                    case_idx, ...
                    overrides.horizon_steps, ...
                    overrides.lambda_sw, ...
                    overrides.min_hold_steps, ...
                    NaN, ...
                    NaN, ...
                    NaN, ...
                    NaN, ...
                    NaN, ...
                    NaN, ...
                    NaN, ...
                    NaN, ...
                    NaN, ...
                    status, ...
                    message, ...
                    toc(t_case)}; %#ok<AGROW>
            end
        end
    end
end

summary_table = cell2table(rows, 'VariableNames', { ...
    'case_idx', ...
    'horizon_steps', ...
    'lambda_sw', ...
    'min_hold_steps', ...
    'valid_steps', ...
    'bubble_steps', ...
    'bubble_fraction', ...
    'bubble_time_s', ...
    'longest_bubble_time_s', ...
    'max_bubble_depth', ...
    'switch_count', ...
    'resource_score', ...
    'min_margin', ...
    'status', ...
    'message', ...
    'elapsed_s'});

disp('=== [ch5r:R5-smoke] parameter scan summary ===')
disp(summary_table)

n_ok = sum(summary_table.status == "ok");
n_err = sum(summary_table.status == "error");

disp(['ok cases    : ' num2str(n_ok)])
disp(['error cases : ' num2str(n_err)])

assert(n_err == 0, '[ch5r:R5-smoke] some scan cases failed.');

if ~isempty(summary_table)
    assert(all(summary_table.valid_steps == 742), ...
        '[ch5r:R5-smoke] valid_steps must stay fixed at 742 under current window semantics.');
    assert(all(summary_table.resource_score == 2), ...
        '[ch5r:R5-smoke] resource_score must stay fixed at 2.');
end

out = struct();
out.summary_table = summary_table;
out.ok = true;
end
