function out = run_ch5r_phase9_alpha_smoke()
%RUN_CH5R_PHASE9_ALPHA_SMOKE
% Minimal alpha-only smoke scan for R9.

alpha_grid = [0, 0.25, 0.5, 1, 2];
rows = {};
for i = 1:numel(alpha_grid)
    alpha = alpha_grid(i);

    overrides = struct();
    overrides.alpha_tau = alpha;
    overrides.save_outputs = false;
    overrides.log_enable = false;

    t_case = tic;
    status = "ok";
    msg = "";

    try
        out9 = run_ch5r_phase9_r9_closedloop(overrides);

        bm = out9.result.bubble_metrics;
        cm = out9.result.cost_metrics;
        tr = out9.result.r9_tracking;

        rows(end+1,:) = { ...
            alpha, ...
            bm.total_valid_steps, ...
            bm.bubble_steps, ...
            bm.bubble_time_s, ...
            bm.longest_bubble_time_s, ...
            bm.max_bubble_depth, ...
            bm.mean_bubble_depth, ...
            cm.switch_count, ...
            tr.mean_rmse_pos_km, ...
            tr.final_rmse_pos_km, ...
            status, ...
            msg, ...
            toc(t_case)}; %#ok<AGROW>

    catch ME
        status = "error";
        msg = string(ME.message);

        rows(end+1,:) = { ...
            alpha, ...
            NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, ...
            status, msg, toc(t_case)}; %#ok<AGROW>
    end
end

T = cell2table(rows, 'VariableNames', { ...
    'alpha_tau', ...
    'valid_steps', ...
    'bubble_steps', ...
    'bubble_time_s', ...
    'longest_bubble_time_s', ...
    'max_bubble_depth', ...
    'mean_bubble_depth', ...
    'switch_count', ...
    'mean_rmse_pos_km', ...
    'final_rmse_pos_km', ...
    'status', ...
    'message', ...
    'elapsed_s'});

disp('=== [ch5r:R9-alpha-smoke] summary ===')
disp(T)

assert(all(T.valid_steps == 742 | isnan(T.valid_steps)));
assert(all(T.status == "ok"));

out = struct();
out.summary_table = T;
out.ok = true;
end
